const CACHE = 'hebe-v194';
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './fonts/fraunces-400.woff2',
  './fonts/fraunces-400-italic.woff2',
  './fonts/fraunces-500.woff2',
  './fonts/fraunces-600.woff2',
  './fonts/outfit-400.woff2',
  './fonts/outfit-500.woff2',
  './fonts/outfit-600.woff2',
  './fonts/outfit-700.woff2',
  './manifest.json',
  './js/app.js',
  './data/migrate.js',
  './data/ingredients.js',
  './data/recipes.js',
  './data/photos.js',
  './data/prefs.js',
  './img/dishes/C01.webp',
  './img/dishes/K01.webp',
  './img/dishes/K02.webp',
  './img/dishes/K03.webp',
  './img/dishes/K05.webp',
  './img/dishes/K06.webp',
  './img/dishes/K07.webp',
  './img/dishes/K08.webp',
  './img/dishes/K09.webp',
  './img/dishes/K10.webp',
  './img/dishes/K11.webp',
  './img/dishes/K12.webp',
  './img/dishes/S02.webp',
  './img/dishes/S05.webp',
  './img/dishes/S07.webp',
  './img/dishes/S08.webp',
  './img/dishes/S09.webp',
  './img/dishes/S11.webp',
  './img/dishes/S12.webp',
  './img/dishes/S16.webp',
  './img/dishes/SA01.webp',
  './img/dishes/SA11.webp',
  './img/dishes/W01.webp',
  './img/dishes/W02.webp',
  './img/dishes/W03.webp',
  './img/dishes/W04.webp',
  './img/dishes/W05.webp',
  './img/dishes/W06.webp',
  './img/dishes/W07.webp',
  './img/dishes/W08.webp',
  './img/dishes/W09.webp',
  './img/dishes/W10.webp',
  './img/dishes/W11.webp',
  './img/dishes/W12.webp',
  './img/dishes/W13.webp',
  './img/dishes/W14.webp',
  './img/dishes/W15.webp',
  './img/dishes/W16.webp',
  './img/dishes/W17.webp',
  './img/dishes/W18.webp',
  './img/dishes/W19.webp',
  './img/dishes/W20.webp',
  './img/dishes/W21.webp',
  './img/dishes/W22.webp',
  './img/dishes/W23.webp',
  './img/dishes/W24.webp',
  './img/dishes/W25.webp',
  './img/dishes/W26.webp',
  './img/dishes/W27.webp',
  './img/dishes/W28.webp',
  './img/dishes/W29.webp',
  './img/dishes/W30.webp',
  './img/dishes/W31.webp',
  './img/dishes/W32.webp',
  './img/dishes/W33.webp',
  './img/dishes/W34.webp',
  './img/dishes/W35.webp',
  './img/dishes/W36.webp',
  './img/dishes/W37.webp',
  './img/dishes/W38.webp',
  './img/dishes/W39.webp',
  './img/dishes/W40.webp',
  './img/dishes/W41.webp',
  './img/dishes/W43.webp',
  './img/dishes/W44.webp',
  './img/dishes/W45.webp',
  './img/dishes/W46.webp',
  './img/dishes/W47.webp',
  './img/dishes/W48.webp',
  './img/dishes/W49.webp',
  './img/dishes/W50.webp',
  './img/dishes/W51.webp',
  './img/dishes/W52.webp',
  './img/dishes/W53.webp',
  './img/dishes/W54.webp',
  './img/dishes/W55.webp',
  './img/dishes/W56.webp',
  './img/dishes/W57.webp',
  './img/dishes/W58.webp',
  './img/dishes/W59.webp',
  './img/dishes/W60.webp',
  './img/dishes/W61.webp',
  './img/dishes/W62.webp',
  './img/dishes/W63.webp',
  './img/dishes/W64.webp',
  './img/dishes/W65.webp',
  './img/dishes/W66.webp',
  './img/dishes/W67.webp',
  './img/dishes/W68.webp',
  './img/dishes/W69.webp',
  './img/dishes/W70.webp',
  './img/dishes/W71.webp',
  './img/dishes/W72.webp',
  './img/dishes/W73.webp',
  './img/dishes/W74.webp',
  './img/dishes/W75.webp',
  './img/dishes/B01.webp',
  './img/dishes/B02.webp',
  './img/dishes/B05.webp',
  './img/dishes/B06.webp',
  './img/dishes/B07.webp',
  './img/dishes/B15.webp',
  './img/dishes/B16.webp',
  './img/dishes/K13.webp',
  './img/dishes/K14.webp',
  './img/dishes/K15.webp',
  './img/dishes/K16.webp',
  './img/dishes/K17.webp',
  './img/dishes/K18.webp',
  './img/dishes/K19.webp',
  './img/dishes/K20.webp',
  './img/dishes/K21.webp',
  './img/art/man.webp',
  './img/art/woman.webp',
  './img/art/man_bowl.webp',
  './img/art/couple.webp',
  './img/art/tablier.webp',
  './img/art/joker.webp',
  './img/art/prot-poulet.webp',
  './img/art/prot-boeuf.webp',
  './img/art/prot-crevettes.webp',
  './img/art/prot-saumon.webp',
  './img/art/prot-tofu.webp',
  './img/art/accueil.webp',
  './img/art/cantine.webp',
  './data/user.js',
  './data/log.js',
  './data/calculator.js',
  './icon-192.png',
  './icon-512.png',
  './icon-192-maskable.png',
  './icon-512-maskable.png',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(response => {
        if (response && response.status === 200 && response.type !== 'opaque') {
          caches.open(CACHE).then(c => c.put(e.request, response.clone()));
        }
        return response;
      }).catch(() => cached);
    })
  );
});
