const R = (id, name, emoji, prep, cook, ings, steps, tip, tags, batch = false) =>
  ({ id, name, cat: 'sweet', emoji, prep, cook, ings, steps, tip, tags, batch });
exports.snacks = [
  R('K01', 'Lassi mangue protéiné', '🥭', 3, 0,
    [['yaourt_grec', 200], ['mangue', 150], ['whey', 25], ['lait', 100], ['epices', 1]],
    ['Tout mixer avec une pincée de cardamome.', 'Servir bien frais.'],
    'Mangue surgelée = texture de milkshake, sans glaçons.', ['indien', 'sucré', 'rapide', 'whey']),
  R('K02', 'Yaourt grec miel-pistache', '🍯', 2, 0,
    [['yaourt_grec', 200], ['whey', 15], ['miel', 12], ['pistaches', 20]],
    ['Mélanger la whey dans le yaourt.', 'Miel et pistaches concassées dessus.'],
    'Le dessert grec de base, version protéinée.', ['grec', 'sucré', 'rapide', 'whey']),
  R('K03', 'Labneh za\'atar, pita & crudités', '🫓', 4, 2,
    [['yaourt_grec', 150], ['huile', 5], ['epices', 2], ['pita', 70], ['concombre', 80], ['tomate', 80]],
    ['Yaourt grec bien épais étalé, huile d\'olive, za\'atar.', 'Pita réchauffée 2 min à l\'air fryer, crudités en bâtonnets.'],
    'La collation salée du Levant, à tremper.', ['libanais', 'salé', 'rapide']),
  R('K05', 'Overnight oats tiramisu', '☕', 4, 0,
    [['flocons', 50], ['lait', 120], ['whey', 25], ['fromage_blanc', 100], ['cacao', 5], ['miel', 8]],
    ['Flocons + lait + whey + 1 c.à.c de café soluble, en bocal.', 'Couche de fromage blanc au miel, cacao en poudre.', 'Une nuit au frigo.'],
    'Prépare 3 bocaux d\'un coup : 4 jours au frigo.', ['italien', 'sucré', 'whey'], true),
  R('K06', 'Pancakes protéinés à la banane', '🥞', 5, 8,
    [['flocons', 50], ['banane', 80], ['oeuf', 1], ['whey', 20], ['lait', 50], ['miel', 10]],
    ['Mixer flocons, banane, œuf, whey, lait.', 'Petits pancakes à la poêle, 1 min 30 par face.', 'Miel ou sirop d\'érable au service.'],
    'Se congèlent : 1 min au grille-pain ou à l\'air fryer.', ['américain', 'sucré', 'whey'], true),
  R('K07', 'Bowl açaí-style fruits rouges', '🫐', 4, 0,
    [['fruits_rouges', 150], ['banane', 80], ['whey', 25], ['lait', 80], ['flocons', 30], ['beurre_cacahuete', 10]],
    ['Mixer fruits rouges surgelés, banane, whey et un peu de lait : texture épaisse.', 'Flocons et beurre de cacahuète dessus.'],
    'Comme au Brésil, mais sans le prix de l\'açaí.', ['brésilien', 'sucré', 'rapide', 'whey']),
  R('K08', 'Energy balls dattes-cacao protéinées', '🟤', 10, 0,
    [['dattes', 30], ['flocons', 25], ['whey', 15], ['beurre_cacahuete', 12], ['cacao', 4]],
    ['Mixer tous les ingrédients, ajouter 1 c.à.s d\'eau si besoin.', 'Rouler en boules (≈ 3 par portion).'],
    'Une fournée pour la semaine : 7 jours au frigo.', ['moyen-orient', 'sucré', 'whey'], true),
  R('K09', 'Shake café-banane-cacahuète', '🥤', 3, 0,
    [['lait', 250], ['whey', 30], ['banane', 100], ['beurre_cacahuete', 15], ['flocons', 20]],
    ['Tout mixer avec 1 c.à.c de café soluble et des glaçons.'],
    'Inspiré du cà phê vietnamien. Se boit en 2 minutes après le sport.', ['vietnamien', 'sucré', 'rapide', 'whey']),
  R('K10', 'Skyr tahini, miel & banane', '🍌', 2, 0,
    [['skyr', 200], ['whey', 10], ['tahini', 15], ['miel', 10], ['banane', 80]],
    ['Skyr + whey.', 'Banane en rondelles, filet de tahini et de miel.'],
    'Le tahini apporte un goût de halva et de bons gras.', ['moyen-orient', 'sucré', 'rapide', 'whey']),
  R('K11', 'Riz au lait coco-mangue protéiné', '🍚', 5, 15,
    [['riz', 40], ['lait', 150], ['lait_coco', 50], ['whey', 20], ['mangue', 100]],
    ['Autocuiseur : riz + lait + lait de coco, 12 min sous pression, dépressurisation naturelle.', 'Laisser tiédir, incorporer la whey.', 'Mangue en dés au service.'],
    'Clin d\'œil au mango sticky rice thaï. 4 jours au frigo.', ['thaï', 'sucré', 'autocuiseur', 'whey'], true),
  R('K12', 'Tostada avocat & œufs', '🥑', 4, 5,
    [['pain', 40], ['avocat', 50], ['oeuf', 2], ['tomate', 60], ['citron_vert', 5], ['epices', 1]],
    ['Pain grillé à l\'air fryer 3 min.', 'Avocat écrasé, citron vert, piment.', 'Œufs brouillés ou au plat, tomate en dés.'],
    'La collation salée qui cale vraiment.', ['mexicain', 'salé', 'rapide']),
];
