const R = (id, name, emoji, prep, cook, ings, steps, tip, tags, batch = false) =>
  ({ id, name, cat: 'sweet', emoji, prep, cook, ings, steps, tip, tags, batch });
exports.snacks = [
  R('K01', 'Lassi mangue protéiné', '🥭', 3, 0,
    [['yaourt_grec', 200], ['mangue', 150], ['whey', 25], ['lait', 100], ['epices', 1]],
    ['Tout mixer avec une pincée de cardamome.', 'Servir bien frais.'],
    'Mangue surgelée = texture de milkshake, sans glaçons.', ['indien', 'sucré', 'rapide', 'whey']),
  R('K02', 'Yaourt grec miel-pistache', '🍯', 2, 0,
    [['yaourt_grec', 200], ['whey', 15], ['miel', 10], ['pistaches', 15]],
    ['Mélanger la whey dans le yaourt.', 'Miel et pistaches concassées dessus.'],
    'Le dessert grec de base, version protéinée.', ['grec', 'sucré', 'rapide', 'whey']),
  R('K03', 'Labneh za\'atar, pita & crudités', '🫓', 4, 2,
    [['yaourt_grec', 150], ['huile', 5], ['epices', 2], ['pita', 70], ['concombre', 80], ['tomate', 80]],
    ['Yaourt grec bien épais étalé, huile d\'olive, za\'atar.', 'Pita réchauffée 2 min à l\'air fryer, crudités en bâtonnets.'],
    'La collation salée du Levant, à tremper.', ['libanais', 'salé', 'rapide']),
  R('K05', 'Overnight oats tiramisu', '☕', 4, 0,
    [['flocons', 40], ['lait', 120], ['whey', 20], ['fromage_blanc', 100], ['cacao', 3], ['miel', 8]],
    ['Flocons + lait + whey + 1 c.à.c de café soluble, en bocal.', 'Couche de fromage blanc au miel, cacao en poudre.', 'Une nuit au frigo.'],
    'À préparer la veille au soir : 4 minutes, et il est prêt le lendemain.', ['italien', 'sucré', 'whey'], false),
  R('K06', 'Pancakes protéinés à la banane', '🥞', 5, 8,
    [['flocons', 40], ['banane', 100], ['oeuf', 1], ['whey', 20], ['lait', 50], ['miel', 8]],
    ['Mixer flocons, banane, œuf, whey, lait.', 'Petits pancakes à la poêle, 1 min 30 par face.', 'Miel ou sirop d\'érable au service.'],
    'Se congèlent : 1 min au grille-pain ou à l\'air fryer.', ['américain', 'sucré', 'whey'], true),
  R('K07', 'Bowl açaí-style fruits rouges', '🫐', 4, 0,
    [['fruits_rouges', 150], ['banane', 80], ['whey', 25], ['lait', 80], ['flocons', 30], ['beurre_cacahuete', 10]],
    ['Mixer fruits rouges surgelés, banane, whey et un peu de lait : texture épaisse.', 'Flocons et beurre de cacahuète dessus.'],
    'Comme au Brésil, mais sans le prix de l\'açaí.', ['brésilien', 'sucré', 'rapide', 'whey']),
  R('K08', 'Energy balls dattes-cacao protéinées', '🟤', 10, 0,
    [['dattes', 40], ['flocons', 25], ['whey', 15], ['beurre_cacahuete', 10], ['cacao', 4]],
    ['Mixer tous les ingrédients, ajouter 1 c.à.s d\'eau si besoin.', 'Rouler en boules (≈ 3 par portion).'],
    'Une fournée pour la semaine : 7 jours au frigo.', ['moyen-orient', 'sucré', 'whey'], true),
  R('K09', 'Shake café-banane-cacahuète', '🥤', 3, 0,
    [['lait', 250], ['whey', 30], ['banane', 100], ['beurre_cacahuete', 15], ['flocons', 20]],
    ['Tout mixer avec 1 c.à.c de café soluble et des glaçons.'],
    'Inspiré du cà phê vietnamien. Se boit en 2 minutes après le sport.', ['vietnamien', 'sucré', 'rapide', 'whey']),
  R('K10', 'Fromage blanc, beurre de cacahuète, miel et banane', '🍌', 2, 0,
    [['fromage_blanc', 250], ['whey', 15], ['beurre_cacahuete', 10], ['miel', 8], ['banane', 80]],
    ['Skyr + whey.', 'Banane en rondelles, filet de tahini et de miel.'],
    'Le tahini apporte un goût de halva et de bons gras.', ['moyen-orient', 'sucré', 'rapide', 'whey']),
  R('K11', 'Riz au lait coco-mangue protéiné', '🍚', 5, 15,
    [['riz', 40], ['lait', 150], ['lait_coco', 50], ['whey', 20], ['mangue', 100]],
    ['Autocuiseur : riz + lait + lait de coco, 12 min sous pression, dépressurisation naturelle.', 'Laisser tiédir, incorporer la whey.', 'Mangue en dés au service.'],
    'Clin d\'œil au mango sticky rice thaï. 4 jours au frigo.', ['thaï', 'sucré', 'autocuiseur', 'whey'], true),
  R('K12', 'Tostada avocat et œuf', '🥑', 4, 5,
    [['pain', 40], ['avocat', 50], ['oeuf', 1], ['tomate', 40], ['citron_vert', 10], ['huile', 3], ['epices', 1]],
    ['Pain grillé à l\'air fryer 3 min.', 'Avocat écrasé, citron vert, piment.', 'Œufs brouillés ou au plat, tomate en dés.'],
    'La collation salée qui cale vraiment.', ['mexicain', 'salé', 'rapide']),
  R('K13', 'Mini-wrap thon et carré frais', '🌯', 2, 0,
    [['tortilla', 60], ['thon', 70], ['carre_frais', 25], ['concombre', 40], ['salade', 10], ['citron', 5]],
    ['Voir les étapes détaillées.'],
    'Une petite boîte de thon suffit pour un wrap.', ['salé', 'rapide']),
  R('K14', 'Croque-monsieur jambon-fromage', '🥪', 2, 7,
    [['pain', 80], ['jambon_blanc', 80], ['emmental', 20], ['moutarde', 3]],
    ['Voir les étapes détaillées.'],
    'Pas de beurre : le fromage gratiné suffit.', ['salé', 'rapide']),
  // ════ Classiques gourmands, version plus légère (v181) ════
  R('K15', 'Roses des sables au beurre de cacahuète', '🌹', 10, 0,
    [['cornflakes', 25], ['chocolat', 15], ['beurre_cacahuete', 10], ['whey', 10]],
    ["Fais fondre le chocolat noir au micro-ondes par tranches de 30 secondes, en remuant entre chaque, jusqu'à ce qu'il soit lisse.",
     "Ajoute le beurre de cacahuète et la whey, et mélange jusqu'à obtenir une pâte brillante.",
     "Ajoute les corn flakes et enrobe-les délicatement à la spatule, sans trop les écraser.",
     "Forme de petits tas sur une feuille de papier cuisson, environ 3 par portion, et laisse-les durcir 30 minutes au frigo.",
     "Mise en boîtes : les roses des sables dans une boîte hermétique, au frigo. Elles se gardent une semaine."],
    "Le chocolat noir et le beurre de cacahuète remplacent le chocolat au lait et la graisse végétale de la recette classique.", ['français', 'sucré', 'sans cuisson', 'semaine', 'whey'], true),
  R('K16', 'Tiramisu minute en verrine', '☕', 5, 0,
    [['boudoirs', 24], ['yaourt_grec', 150], ['whey', 15], ['miel', 5], ['cacao', 3]],
    ["Trempe rapidement les boudoirs dans un fond de café froid, une seconde de chaque côté, et pose-les au fond d'un verre.",
     "Mélange le yaourt grec, la whey et le miel jusqu'à ce que ce soit lisse, puis verse sur les boudoirs.",
     "Saupoudre de cacao. Mange tout de suite, ou garde le verre une heure au frigo pour que les boudoirs s'imbibent."],
    "Le yaourt grec et la whey remplacent le mascarpone et les œufs : même goût, trois fois plus de protéines.", ['italien', 'sucré', 'sans cuisson', 'rapide', 'whey']),
  R('K17', 'Barres de céréales aux dattes et aux cacahuètes', '🌾', 10, 0,
    [['dattes', 30], ['flocons', 25], ['cacahuetes', 12], ['whey', 10], ['cacao', 3]],
    ["Mixe les dattes avec une cuillère à soupe d'eau chaude, jusqu'à obtenir une pâte collante.",
     "Ajoute les flocons d'avoine, la whey et le cacao, et mixe quelques secondes seulement, pour garder des morceaux de flocons.",
     "Incorpore les cacahuètes entières à la main : ce sont elles qui donnent le croquant.",
     "Tasse le tout dans une petite boîte tapissée de papier cuisson, sur 1,5 cm d'épaisseur, et laisse prendre une heure au frigo.",
     "Mise en boîtes : coupe en barres, une par portion, et garde-les au frigo. Elles se gardent une semaine."],
    "Les dattes font tout le travail du sucre et de la liaison : aucun sucre ajouté.", ['français', 'sucré', 'sans cuisson', 'semaine', 'whey'], true),
  R('K18', 'Barres façon Snickers aux dattes', '🍫', 15, 0,
    [['dattes', 30], ['whey', 10], ['beurre_cacahuete', 12], ['cacahuetes', 10], ['chocolat', 12]],
    ["Mixe les dattes avec la whey et une cuillère à soupe d'eau chaude : c'est le « caramel ». Étale-le sur 1 cm dans une petite boîte tapissée de papier cuisson.",
     "Étale le beurre de cacahuète par-dessus, puis parsème de cacahuètes concassées en appuyant légèrement.",
     "Fais fondre le chocolat noir au micro-ondes par tranches de 30 secondes et verse-le sur le dessus en une fine couche.",
     "Laisse prendre une heure au congélateur, puis coupe en barres, une par portion.",
     "Mise en boîtes : les barres dans une boîte au congélateur. Sors-en une 10 minutes avant de la manger."],
    "Le caramel de dattes remplace le caramel au sucre : même texture fondante, avec des fibres en plus.", ['américain', 'sucré', 'sans cuisson', 'semaine', 'whey'], true),
  R('K19', 'Bouchées façon Bounty', '🥥', 15, 0,
    [['coco_rapee', 20], ['lait_coco', 20], ['whey', 12], ['miel', 8], ['chocolat', 10]],
    ["Mélange la noix de coco râpée, le lait de coco, la whey et le miel jusqu'à obtenir une pâte qui se tient. Si elle colle trop, ajoute une pincée de coco.",
     "Forme de petites bouchées allongées, environ 3 par portion, pose-les sur du papier cuisson et laisse-les durcir 20 minutes au congélateur.",
     "Fais fondre le chocolat noir au micro-ondes par tranches de 30 secondes, trempe chaque bouchée dedans et repose-la sur le papier.",
     "Mise en boîtes : les bouchées dans une boîte au congélateur. Sors-les 5 minutes avant de les manger."],
    "Le lait de coco et un peu de miel remplacent le lait concentré sucré : tout le goût du Bounty, avec bien moins de sucre.", ['sucré', 'sans cuisson', 'semaine', 'whey'], true),
  R('K20', 'Barres granola croustillantes à l\'air fryer', '🥜', 10, 12,
    [['flocons', 30], ['amandes', 12], ['whey', 10], ['beurre_cacahuete', 8], ['miel', 10]],
    ["Concasse grossièrement les amandes et mélange-les avec les flocons d'avoine et la whey.",
     "Fais tiédir le miel et le beurre de cacahuète 20 secondes au micro-ondes, puis verse-les sur les flocons et mélange bien, jusqu'à ce que tout soit enrobé.",
     "Tasse la préparation sur 1,5 cm d'épaisseur sur une feuille de papier cuisson posée dans le panier de l'air fryer.",
     "Fais cuire 12 minutes à 160 °C, jusqu'à ce que ce soit doré. Laisse refroidir complètement avant de couper : les barres durcissent en refroidissant.",
     "Mise en boîtes : une barre par portion, dans une boîte hermétique. Elles se gardent une semaine."],
    "Bien les laisser refroidir avant de les couper, sinon elles s'émiettent.", ['américain', 'sucré', 'air fryer', 'semaine', 'whey'], true),
  R('K21', 'Cookies banane et pépites de chocolat à l\'air fryer', '🍪', 10, 8,
    [['banane', 50], ['flocons', 30], ['whey', 15], ['chocolat', 10]],
    ["Écrase la banane à la fourchette, puis mélange-la avec les flocons d'avoine et la whey.",
     "Ajoute le chocolat noir haché en petits morceaux.",
     "Forme 3 cookies par portion, aplatis-les à 1 cm et pose-les sur du papier cuisson dans le panier de l'air fryer.",
     "Fais-les cuire 8 minutes à 170 °C : ils doivent être dorés sur les bords et encore moelleux au centre. Laisse-les refroidir 10 minutes, ils se raffermissent.",
     "Mise en boîtes : les cookies dans une boîte, 3 jours au frigo, ou au congélateur pour la semaine. Réchauffe-les 2 minutes à l'air fryer à 160 °C."],
    "La banane bien mûre remplace le beurre et le sucre.", ['américain', 'sucré', 'air fryer', 'semaine', 'whey'], true),
];