const R = (id, name, cat, emoji, prep, cook, ings, steps, tip, tags, batch = true) => ({ id, name, cat, emoji, prep, cook, ings, steps, tip, tags, batch });

exports.mains = [
  R('M01', 'Pâtes bolognaise', 'dinner', '🍝', 10, 25,
    [['boeuf', 130], ['pates', 90], ['tomates_conc', 150], ['carotte', 60], ['oignon', 50], ['ail', 1], ['huile', 5], ['epices', 2]],
    ['Émincer oignon, ail et carotte, faire revenir 5 min dans l\'huile.', 'Ajouter le bœuf, cuire 5 min en l\'émiettant.', 'Ajouter les tomates + origan, mijoter 15 min.', 'Cuire les pâtes, mélanger ou garder séparé pour les boîtes.'],
    'La sauce se congèle très bien : fais-en une double dose.', ['batch', 'économique', 'classique']),
  R('M02', 'Hachis parmentier & haricots verts', 'dinner', '🥔', 15, 30,
    [['boeuf', 140], ['pdt', 300], ['lait', 60], ['emmental', 15], ['oignon', 50], ['haricots_verts', 150]],
    ['Cuire les pommes de terre à l\'eau 20 min, écraser avec le lait.', 'Faire revenir l\'oignon puis le bœuf 6 min, saler, poivrer.', 'Plat : bœuf au fond, purée dessus, emmental. Four 200°C 10 min.', 'Haricots verts à la poêle à côté.'],
    'Se coupe en parts nettes : parfait en boîtes. Se garde 3 jours, se congèle.', ['batch', 'four', 'classique']),
  R('M03', 'Chili sin carne & riz', 'dinner', '🌶️', 10, 25,
    [['haricots_rouges', 150], ['mais', 50], ['tomates_conc', 150], ['poivron', 100], ['oignon', 50], ['riz', 70], ['yaourt_grec', 60], ['epices', 5], ['huile', 5]],
    ['Faire revenir oignon et poivron 5 min.', 'Ajouter épices (cumin, paprika), tomates, haricots égouttés, maïs.', 'Mijoter 15 min. Cuire le riz.', 'Servir avec une cuillère de yaourt grec.'],
    'Le plat le moins cher de la liste. Encore meilleur le lendemain.', ['batch', 'végé', 'économique']),
  R('M04', 'Curry pois chiches-épinards & riz', 'dinner', '🍛', 5, 20,
    [['pois_chiches', 180], ['epinards', 150], ['lait_coco', 80], ['tomates_conc', 100], ['oignon', 50], ['pate_curry', 15], ['riz', 70]],
    ['Faire revenir l\'oignon avec la pâte de curry 2 min.', 'Ajouter tomates, lait de coco et pois chiches égouttés, 10 min.', 'Ajouter les épinards, 5 min.', 'Servir sur le riz.'],
    'Tout en placard/congélateur : idéal en fin de semaine quand le frais manque.', ['batch', 'végé', 'économique']),
  R('M05', 'Poulet basquaise & riz', 'dinner', '🫑', 10, 25,
    [['poulet', 150], ['poivron', 150], ['tomates_conc', 120], ['oignon', 50], ['riz', 75], ['ail', 1], ['huile', 5], ['epices', 2]],
    ['Dorer le poulet en morceaux dans l\'huile, réserver.', 'Faire fondre oignon, ail et poivrons 8 min.', 'Ajouter tomates, paprika, remettre le poulet, mijoter 12 min.', 'Servir avec le riz.'],
    'Mijoté = se réchauffe sans dessécher le poulet.', ['batch', 'mijoté']),
  R('M06', 'Poulet moutarde, pâtes & haricots verts', 'dinner', '🍗', 5, 15,
    [['poulet', 150], ['pates', 80], ['haricots_verts', 150], ['creme', 40], ['moutarde', 10]],
    ['Cuire les pâtes et les haricots verts.', 'Saisir le poulet en lamelles 6 min.', 'Ajouter crème + moutarde, laisser épaissir 2 min.', 'Mélanger le tout.'],
    'Une sauce crémeuse avec seulement 40 ml de crème légère.', ['batch', 'rapide']),
  R('M07', 'Gratin de pâtes au thon & brocoli', 'dinner', '🧀', 10, 25,
    [['pates', 85], ['thon', 110], ['brocoli', 150], ['lait', 100], ['carre_frais', 25], ['emmental', 20]],
    ['Cuire pâtes et brocoli ensemble (brocoli les 4 dernières minutes).', 'Mélanger avec thon, lait et carré frais.', 'Plat à gratin, emmental dessus, four 200°C 15 min.'],
    'Thon en boîte = pas de stress de date limite. Se coupe en parts.', ['batch', 'four', 'économique']),
  R('M08', 'Tortilla espagnole & salade', 'dinner', '🍳', 10, 25,
    [['oeuf', 4], ['pdt', 250], ['oignon', 60], ['huile', 8], ['salade', 60], ['tomates_cerise', 80]],
    ['Pommes de terre en fines rondelles + oignon, cuire à la poêle couverte 15 min.', 'Battre les œufs, verser sur les pommes de terre.', 'Cuire 5 min, retourner avec une assiette, 3 min.', 'Servir tiède ou froide avec la salade.'],
    'Se mange froide : la championne des boîtes repas.', ['batch', 'œufs', 'économique']),
  R('M09', 'Riz cantonais poulet-œuf', 'dinner', '🍚', 10, 15,
    [['poulet', 120], ['riz', 80], ['oeuf', 2], ['petits_pois', 100], ['carotte', 60], ['soja', 15], ['huile', 5]],
    ['Cuire le riz (idéalement la veille, il saute mieux).', 'Poêle : poulet en dés 5 min, réserver.', 'Œufs brouillés rapides, puis carotte et petits pois 4 min.', 'Tout remettre avec le riz et la sauce soja, 3 min à feu vif.'],
    'Recette anti-gaspi par excellence : marche avec n\'importe quel reste de légumes.', ['batch', 'asiatique', 'rapide']),
  R('M10', 'Couscous poulet & légumes', 'dinner', '🥘', 10, 25,
    [['poulet', 140], ['semoule', 75], ['pois_chiches', 60], ['carotte', 80], ['courgette', 120], ['tomates_conc', 80], ['epices', 5], ['huile', 5]],
    ['Dorer le poulet avec ras el hanout.', 'Ajouter carottes, courgettes, tomates, pois chiches + 200 ml d\'eau, mijoter 20 min.', 'Semoule : volume égal d\'eau bouillante, couvrir 5 min, égrainer.'],
    'Garder la semoule à part dans les boîtes, elle reste plus légère.', ['batch', 'mijoté']),
  R('M11', 'Lentilles mijotées & œufs mollets', 'dinner', '🥚', 10, 25,
    [['lentilles_vertes', 80], ['oeuf', 2], ['carotte', 100], ['oignon', 50], ['tomates_conc', 80], ['bouillon', 1], ['huile', 5]],
    ['Faire revenir oignon et carottes 5 min.', 'Ajouter lentilles, tomates, bouillon + 3× leur volume d\'eau, 20-25 min.', 'Œufs mollets : 6 min dans l\'eau bouillante, puis eau froide.', 'Servir les œufs écalés sur les lentilles.'],
    'Les œufs se cuisent pour 3 jours d\'un coup et se gardent écalés au frigo.', ['batch', 'végé', 'économique']),
  R('M12', 'Pâtes poulet-champignons', 'dinner', '🍄', 10, 15,
    [['poulet', 140], ['pates', 85], ['champignons', 150], ['epinards', 80], ['oignon', 40], ['creme', 40]],
    ['Cuire les pâtes.', 'Saisir le poulet 5 min, réserver.', 'Oignon + champignons 6 min, puis épinards 2 min.', 'Crème, poulet, pâtes : mélanger.'],
    'Ajoute un peu d\'eau de cuisson des pâtes au réchauffage pour garder le crémeux.', ['batch', 'rapide']),
  R('M13', 'Shakshuka & pain', 'dinner', '🍅', 5, 20,
    [['oeuf', 3], ['tomates_conc', 200], ['poivron', 120], ['oignon', 50], ['feta', 20], ['pain', 80], ['huile', 6], ['epices', 3]],
    ['Oignon + poivron 8 min, ajouter tomates, cumin, paprika, 8 min.', 'Creuser des puits, casser les œufs, couvrir 5-6 min.', 'Émietter la feta, servir avec le pain.'],
    'En batch : prépare la sauce pour 3 jours, cuis les œufs dedans au moment de manger (5 min).', ['batch', 'œufs', 'économique']),
  R('M14', 'Boulettes de poulet, sauce tomate & semoule', 'dinner', '🧆', 15, 20,
    [['poulet_hache', 150], ['chapelure', 15], ['tomates_conc', 150], ['courgette', 120], ['semoule', 70], ['epices', 3]],
    ['Mélanger poulet haché, chapelure, épices ; former des boulettes.', 'Les dorer 5 min à la poêle.', 'Ajouter tomates et courgettes en dés, mijoter 12 min.', 'Semoule à côté.'],
    'Les boulettes crues se congèlent sur une plaque puis en sachet.', ['batch', 'mijoté']),
  R('M15', 'Poulet citron, pommes de terre & carottes au four', 'dinner', '🍋', 10, 35,
    [['poulet', 150], ['pdt', 250], ['carotte', 120], ['huile', 8], ['citron', 15], ['ail', 1], ['epices', 3]],
    ['Pommes de terre et carottes en morceaux, huile, thym, ail. Four 200°C 15 min.', 'Ajouter le poulet en morceaux + jus de citron.', 'Encore 20 min au four.'],
    'Une seule plaque, zéro surveillance. Double la plaque pour la semaine.', ['batch', 'four']),
  R('M16', 'Colin à la provençale & riz', 'dinner', '🐟', 5, 20,
    [['poisson_blanc', 170], ['riz', 75], ['tomates_conc', 120], ['courgette', 120], ['oignon', 40], ['huile', 8], ['epices', 2]],
    ['Oignon + courgettes 5 min, ajouter tomates et herbes de Provence, 5 min.', 'Poser le poisson dessus, couvrir 8-10 min.', 'Servir avec le riz.'],
    'Poisson surgelé = le poisson le moins cher. À manger dans les 2 jours une fois cuit.', ['batch', 'poisson']),
  R('M17', 'Wok de bœuf, nouilles & légumes', 'dinner', '🥢', 10, 12,
    [['boeuf', 130], ['nouilles_riz', 75], ['poivron', 100], ['carotte', 60], ['brocoli', 100], ['soja', 15], ['ail', 1], ['huile', 5]],
    ['Tremper ou cuire les nouilles.', 'Wok très chaud : bœuf 4 min, réserver.', 'Légumes 5 min, ail, soja.', 'Tout mélanger avec les nouilles.'],
    'Les légumes surgelés pour wok font très bien l\'affaire.', ['batch', 'asiatique', 'rapide']),
  R('M18', 'Mafé de poulet & riz', 'dinner', '🥜', 10, 25,
    [['poulet', 140], ['beurre_cacahuete', 15], ['tomates_conc', 120], ['carotte', 80], ['oignon', 50], ['riz', 70], ['epices', 2]],
    ['Dorer le poulet et l\'oignon.', 'Ajouter carottes, tomates, beurre de cacahuète délayé dans 150 ml d\'eau.', 'Mijoter 20 min. Servir avec le riz.'],
    'Version légère du classique sénégalais : 15 g de beurre de cacahuète suffisent pour le goût.', ['batch', 'mijoté']),
  R('M19', 'Pâtes pesto, poulet & tomates cerise', 'lunch', '🌿', 5, 12,
    [['poulet', 130], ['pates', 85], ['pesto', 20], ['tomates_cerise', 120], ['courgette', 100]],
    ['Cuire les pâtes.', 'Poulet en dés + courgettes à la poêle 7 min.', 'Mélanger avec pesto et tomates cerise coupées.'],
    'Se mange chaud ou froid en salade : parfait à emporter.', ['batch', 'rapide', 'à emporter']),
  R('M20', 'Tofu sauté, riz & sauce cacahuète', 'dinner', '🥢', 10, 15,
    [['tofu', 160], ['riz', 70], ['brocoli', 120], ['carotte', 60], ['soja', 15], ['beurre_cacahuete', 10]],
    ['Tofu en cubes, bien sécher, dorer 8 min.', 'Brocoli et carottes 5 min.', 'Sauce : soja + beurre de cacahuète + 2 c.à.s d\'eau.', 'Napper, servir sur le riz.'],
    'Le tofu doré se garde 4 jours et reste croustillant au réchauffage à la poêle.', ['batch', 'végé']),
  R('M21', 'Salade de pâtes thon, maïs & crudités', 'lunch', '🥗', 10, 10,
    [['pates', 80], ['thon', 100], ['mais', 50], ['tomates_cerise', 100], ['concombre', 80], ['yaourt_grec', 40], ['moutarde', 5], ['huile', 6]],
    ['Cuire les pâtes, rincer à l\'eau froide.', 'Sauce : yaourt + moutarde + huile.', 'Tout mélanger.'],
    'Zéro réchauffage : idéal au bureau. Se garde 3 jours.', ['batch', 'froid', 'à emporter', 'économique']),
  R('M22', 'Poulet tikka & boulghour', 'dinner', '🍗', 10, 20,
    [['poulet', 150], ['yaourt_grec', 60], ['epices', 5], ['boulghour', 75], ['chou_fleur', 150], ['ail', 1], ['huile', 5]],
    ['Mariner le poulet dans yaourt + épices tikka (10 min ou la veille).', 'Cuire à la poêle 8 min ou au four 15 min.', 'Chou-fleur rôti au four en même temps.', 'Boulghour 12 min.'],
    'La marinade au yaourt garde le poulet tendre même réchauffé.', ['batch']),
  R('M23', 'Parmentier de lentilles', 'dinner', '🥧', 15, 30,
    [['lentilles_vertes', 70], ['pdt', 250], ['carotte', 80], ['oignon', 50], ['lait', 60], ['emmental', 20]],
    ['Cuire les lentilles 20 min avec carottes et oignon.', 'Purée de pommes de terre au lait.', 'Lentilles au fond, purée, emmental. Four 200°C 10 min.'],
    'Version végé du parmentier, très rassasiante et quasi gratuite.', ['batch', 'végé', 'économique', 'four']),
];

exports.snacks = [
  R('SN04', 'Skyr, banane & amandes', 'sweet', '🍌', 2, 0,
    [['skyr', 200], ['banane', 100], ['amandes', 15]],
    ['Skyr dans un bol.', 'Banane en rondelles, amandes concassées.'],
    'Sans whey, 25 g de protéines.', ['encas', 'sucré', 'rapide', '0-cuisson'], false),
  R('SN05', 'Pomme, yaourt grec & cacahuète', 'sweet', '🍎', 3, 0,
    [['yaourt_grec', 150], ['pomme', 150], ['beurre_cacahuete', 15], ['epices', 1]],
    ['Pomme en dés sur le yaourt.', 'Beurre de cacahuète + cannelle.'],
    'Croquant, sucré, protéiné.', ['encas', 'sucré', 'rapide', '0-cuisson'], false),
  R('SN06', 'Tartine thon-carré frais', 'sweet', '🥪', 3, 0,
    [['pain', 60], ['thon', 70], ['carre_frais', 25], ['concombre', 60]],
    ['Écraser le thon avec le carré frais.', 'Tartiner, rondelles de concombre.'],
    'Le salé express qui cale vraiment.', ['encas', 'salé', 'rapide', '0-cuisson'], false),
  R('SN07', 'Œufs durs, pain & fruit', 'sweet', '🥚', 2, 0,
    [['oeuf', 2], ['pain', 50], ['fruit_saison', 150]],
    ['Œufs durs cuits à l\'avance (10 min, se gardent 5 jours).', 'Avec le pain et un fruit.'],
    'Cuis 6-8 œufs le dimanche : collations prêtes pour la semaine.', ['encas', 'salé', 'rapide'], false),
  R('SN08', 'Pain, houmous, poulet & crudités', 'sweet', '🥕', 4, 0,
    [['pain', 60], ['houmous', 40], ['poulet_tranches', 50], ['carotte', 80], ['concombre', 60]],
    ['Tartiner le houmous.', 'Blanc de poulet dessus, crudités en bâtonnets à côté.'],
    'Collation salée et équilibrée.', ['encas', 'salé', 'rapide', '0-cuisson'], false),
  R('SN09', 'Porridge banane', 'sweet', '🥣', 2, 4,
    [['flocons', 50], ['lait', 200], ['banane', 80], ['whey', 15]],
    ['Flocons + lait, 3-4 min à feu doux (ou micro-ondes 2 min).', 'Hors du feu, ajouter la whey, puis la banane.'],
    'Chaud et réconfortant en hiver.', ['encas', 'sucré', 'rapide'], false),
];

exports.sides = [
  R('S05', 'Fruit de saison', 'side', '🍐', 1, 0, [['fruit_saison', 150]], ['À croquer.'], 'Pomme, poire, clémentines… le moins cher selon la saison.', ['fruit', '0-cuisson'], false),
  R('S06', 'Pain complet', 'side', '🍞', 0, 0, [['pain', 40]], ['Une tranche.'], '', ['0-cuisson'], false),
  R('S08', 'Fromage blanc, miel & cacahuète', 'side', '🍯', 1, 0, [['fromage_blanc', 150], ['miel', 8], ['beurre_cacahuete', 5]], ['Un bol de fromage blanc, un filet de miel, une cuillère de beurre de cacahuète.'], '', ['0-cuisson', 'complément'], false),
  R('S09', 'Banane & beurre de cacahuète', 'side', '🍌', 1, 0, [['banane', 100], ['beurre_cacahuete', 15]], ['Banane en rondelles, une cuillère de beurre de cacahuète.'], '', ['0-cuisson', 'complément'], false),
  R('S11', 'Tartine carré frais & blanc de poulet', 'side', '🥪', 2, 0, [['pain', 40], ['carre_frais', 25], ['poulet_tranches', 80]], ['Tartiner, ajouter les tranches de blanc de poulet.'], '', ['0-cuisson', 'complément', 'salé'], false),
  R('S12', 'Tartine carré frais, miel & thym', 'side', '🍯', 1, 0, [['pain', 40], ['carre_frais', 25], ['miel', 8], ['herbes', 1]], ['Tartiner le carré frais, filet de miel, thym (frais ou séché), un tour de poivre.'], 'Le sucré-salé qui marche toujours.', ['0-cuisson', 'complément', 'sucré'], false),
  R('S16', 'Skyr & fruits rouges', 'side', '🫐', 1, 0, [['skyr', 150], ['fruits_rouges', 80]], ['Skyr nature, fruits rouges décongelés ou frais.'], '', ['0-cuisson', 'complément', 'sucré'], false),
  R('S07', "Poignée d'amandes", 'side', '🌰', 0, 0, [['amandes', 25]], ['Une petite poignée (≈ 20 amandes).'], 'Les bons gras qui manquent souvent quand les plats sont maigres.', ['0-cuisson', 'oléagineux'], false),
];

exports.special = [
  R('X01', 'Repas à l\'extérieur', 'extra', '🍽️', 0, 0, [['repas_ext', 3]],
    ['Repas pris au restaurant, chez des amis ou au travail.'],
    'Estimation moyenne : les collations des jours suivants compensent si besoin.', ['imprevu', 'fixe'], false),
];
