// Nouveaux plats (v174) — recherches de tendances « fit et gourmand » d'octobre 2026, adaptées à Hébé :
// plaques, autocuiseur, air fryer (pas de four), ingrédients de supermarché courant, jamais de dinde.
// Même format que plats_du_monde.js ; les étapes sont ici complètes (pas d'entrée dans STEPS de generer.js).
const R = (id, name, cat, emoji, prep, cook, ings, steps, tip, tags, extra = {}) =>
  ({ id, name, cat, emoji, prep, cook, ings, steps, tip, tags, batch: true, ...extra });

// textes communs
const PATES_AC = "Fais cuire les pâtes à l'autocuiseur : couvre-les d'eau juste à hauteur avec une pincée de sel, et fais-les cuire sous pression la moitié du temps indiqué sur le paquet, arrondi en dessous (5 minutes pour des pâtes complètes à 10 ou 11 minutes). Fais tomber la pression et égoutte, en gardant 3 cuillères à soupe d'eau de cuisson par portion.";
const QUINOA_AC = "Rince le quinoa dans une passoire fine, puis mets-le dans l'autocuiseur avec 1,7 fois son poids d'eau et une pincée de sel. Ferme, laisse cuire 1 minute sous pression, puis laisse la pression retomber seule pendant 10 minutes. Égrène-le à la fourchette.";
const BOULGOUR_AC = "Fais cuire le boulgour à l'autocuiseur avec 1,5 fois son volume d'eau et une pincée de sel : 4 minutes sous pression, puis 5 minutes de décompression naturelle. Égrène-le à la fourchette.";
const CREVETTES_VEILLE = "La veille, mets les crevettes à décongeler au frigo. Égoutte-les et sèche-les bien dans un torchon.";

const RIZ_AC = "Riz : rince-le à l'eau froide, puis mets-le dans l'autocuiseur avec 1,7 fois son poids d'eau (par exemple 150 ml d'eau pour 90 g de riz). Ferme, laisse cuire 20 minutes sous pression, puis laisse la pression retomber seule pendant 10 minutes avant d'ouvrir. Mets-le en boîtes dès qu'il a tiédi : le riz cuit ne doit pas rester plus d'une heure à température ambiante.";
const NOUILLES_AC = "Fais cuire les nouilles aux œufs à l'autocuiseur : couvre-les d'eau juste à hauteur avec une pincée de sel, et fais-les cuire sous pression la moitié du temps indiqué sur le paquet, arrondi en dessous. Fais tomber la pression et égoutte.";
const REWARM = "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 2 cuillères à soupe d'eau, en remuant à mi-temps, jusqu'à ce que ce soit bien chaud partout.";

exports.mains = [
  // ════ Lot 1 : pâtes, pommes de terre, céréales, pain ════
  R('W46', 'Mac and cheese au poulet barbecue-miel', 'dinner', '🧀', 10, 20,
    [['poulet', 150], ['pates', 90], ['brocoli', 100], ['lait', 150], ['fecule', 6], ['emmental', 30], ['concentre', 15], ['miel', 8], ['vinaigre_cidre', 5], ['soja', 5], ['epices', 2], ['huile', 5]],
    ["Coupe le poulet en dés de 2 cm. Mélange le concentré de tomate, le miel, le vinaigre de cidre, la sauce soja, le paprika fumé, l'ail en poudre et 2 cuillères à soupe d'eau : c'est la sauce barbecue.",
     "Fais cuire le poulet 6 à 7 minutes à la poêle avec l'huile, jusqu'à ce qu'il ne soit plus rose au centre. Verse la sauce barbecue et laisse réduire 2 minutes en remuant, pour bien enrober chaque morceau. Réserve-le dans une assiette.",
     "Fais cuire les pâtes à l'autocuiseur : couvre-les d'eau juste à hauteur avec une pincée de sel, pose le brocoli par-dessus, et fais-les cuire sous pression la moitié du temps indiqué sur le paquet, arrondi en dessous (5 minutes pour des pâtes complètes à 10 ou 11 minutes). Fais tomber la pression et égoutte.",
     "Dans la poêle rincée, délaye la fécule dans le lait froid, puis fais chauffer à feu moyen en remuant sans arrêt, 3 à 4 minutes, jusqu'à ce que la sauce nappe la cuillère. Hors du feu, ajoute l'emmental et remue jusqu'à ce qu'il fonde.",
     "Mélange les pâtes et le brocoli à la sauce au fromage, puis dispose le poulet barbecue par-dessus.",
     "Mise en boîtes : le mac and cheese avec le poulet par-dessus, au frigo dès qu'il a tiédi.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 2 cuillères à soupe de lait, en remuant à mi-temps, jusqu'à ce que ce soit bien chaud partout."],
    "Une cuillère de lait au réchauffage rend la sauce aussi crémeuse que le premier jour.", ['américain', 'gourmand', 'autocuiseur', 'poêle', 'batch']),

  R('W47', 'Pâtes crémeuses à la feta et aux tomates cerises, crevettes', 'dinner', '🍝', 10, 15,
    [['crevettes', 150], ['pates', 90], ['tomates_cerise', 200], ['feta', 40], ['epinards', 60], ['ail', 1], ['huile', 8], ['citron', 10], ['epices', 1]],
    [CREVETTES_VEILLE,
     "Dans la poêle, fais chauffer l'huile d'olive à feu moyen. Ajoute les tomates cerises entières et l'ail écrasé, couvre et laisse cuire 8 minutes, jusqu'à ce que les tomates éclatent.",
     "Ajoute la feta émiettée, écrase les tomates et la feta à la fourchette et mélange 1 minute : la sauce devient crémeuse.",
     "Ajoute les crevettes, les épinards et l'origan, et laisse cuire 3 minutes, jusqu'à ce que les crevettes soient bien roses. Arrose de jus de citron.",
     PATES_AC + " Mélange-les à la sauce avec l'eau de cuisson gardée.",
     "Mise en boîtes : les pâtes aux crevettes, au frigo dès qu'elles ont tiédi. Avec des crevettes, elles se gardent 2 jours.",
     "Au moment de manger : réchauffe 2 minutes 30 au micro-ondes à puissance moyenne avec 2 cuillères à soupe d'eau, en remuant à mi-temps, sans trop chauffer pour que les crevettes restent tendres."],
    "La feta fond dans le jus des tomates : pas besoin de crème pour une sauce onctueuse.", ['méditerranéen', 'gourmand', 'poêle', 'autocuiseur', 'batch']),

  R('W48', 'Pâtes façon lasagne au cottage cheese', 'dinner', '🍅', 10, 15,
    [['boeuf', 150], ['pates', 90], ['tomates_conc', 200], ['concentre', 15], ['oignon', 50], ['carotte', 50], ['ail', 1], ['epices', 2], ['cottage', 100], ['emmental', 20], ['huile', 3]],
    ["Hache l'oignon, râpe finement la carotte et écrase l'ail.",
     "Dans l'autocuiseur en mode dorer, fais revenir l'oignon et la carotte 3 minutes dans l'huile, puis ajoute le bœuf et fais-le dorer 4 minutes en l'émiettant avec une spatule.",
     "Ajoute l'ail, l'origan, le concentré, les tomates, les pâtes et juste assez d'eau pour les couvrir à hauteur, avec une pincée de sel. Mélange bien et gratte le fond, pour qu'aucune pâte n'y colle.",
     "Ferme et fais cuire sous pression la moitié du temps indiqué sur le paquet, arrondi en dessous (5 minutes pour des pâtes complètes à 10 ou 11 minutes), puis fais tomber la pression.",
     "Hors du feu, ajoute le cottage cheese et l'emmental, et mélange doucement : ils remplacent la béchamel et donnent le goût des lasagnes.",
     "Mise en boîtes : les pâtes, au frigo dès qu'elles ont tiédi.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 2 cuillères à soupe d'eau, en remuant à mi-temps, jusqu'à ce que ce soit bien chaud partout."],
    "Tout cuit dans la même cuve : les pâtes absorbent la sauce et le goût de la viande.", ['italien', 'gourmand', 'autocuiseur', 'batch']),

  R('W49', 'Bouchées de saumon croustillantes, grenailles et sauce yaourt', 'dinner', '🐟', 15, 28,
    [['saumon', 140], ['pdt', 250], ['haricots_verts', 100], ['fecule', 5], ['huile', 8], ['epices', 2], ['yaourt_grec', 80], ['herbes', 5], ['citron', 10], ['ail', 1]],
    ["Coupe les pommes de terre en deux avec la peau, sèche-les dans un torchon et mélange-les avec 5 ml d'huile et une pincée de sel. Fais-les cuire 18 à 20 minutes à l'air fryer à 200 °C, en secouant le panier à mi-cuisson.",
     "Retire la peau du saumon et coupe-le en cubes de 3 cm. Mélange-les avec le reste de l'huile, la fécule, le paprika, l'ail en poudre et une pincée de sel.",
     "Fais cuire les bouchées 7 à 8 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson : elles doivent être dorées dehors et juste nacrées au centre.",
     "Pendant ce temps, fais cuire les haricots verts 6 minutes à la poêle avec un fond d'eau, à couvert, puis laisse l'eau s'évaporer.",
     "Prépare la sauce : le yaourt, l'aneth et la ciboulette ciselés, le jus de citron, une demi-gousse d'ail écrasée, du sel et du poivre.",
     "Mise en boîtes : le saumon, les pommes de terre et les haricots ensemble, la sauce dans un petit pot. Le saumon se garde 2 jours au frigo.",
     "Au moment de manger : réchauffe 4 minutes à l'air fryer à 180 °C pour que tout redevienne croustillant, ou 2 minutes au micro-ondes. Ajoute la sauce froide."],
    "La fécule donne une croûte fine qui reste croustillante au réchauffage à l'air fryer.", ['scandinave', 'air fryer', 'batch', 'poisson']),

  R('W50', 'Poulet miel-moutarde à la crème, pommes de terre et carottes rôties', 'dinner', '🍯', 10, 22,
    [['poulet', 160], ['pdt', 250], ['carotte', 120], ['moutarde', 15], ['miel', 10], ['creme', 20], ['ail', 1], ['huile', 8], ['epices', 1], ['citron', 5]],
    ["Coupe les pommes de terre en cubes de 2 cm avec la peau et les carottes en bâtonnets. Mélange-les avec 5 ml d'huile, le thym et une pincée de sel, et fais-les cuire 20 minutes à l'air fryer à 200 °C, en secouant le panier toutes les 7 minutes.",
     "Mélange la moutarde, le miel, l'ail écrasé, le jus de citron et 2 cuillères à soupe d'eau.",
     "Coupe le poulet en morceaux de 3 cm et fais-le cuire 6 à 7 minutes à la poêle avec le reste de l'huile, jusqu'à ce qu'il soit doré et plus rose au centre.",
     "Verse la sauce miel-moutarde dans la poêle et laisse-la réduire 2 minutes en remuant. Hors du feu, ajoute la crème fraîche et mélange : la sauce devient onctueuse et nappe le poulet.",
     "Mise en boîtes : le poulet avec sa sauce sur les pommes de terre et les carottes.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes en remuant à mi-temps, ou 5 minutes à l'air fryer à 180 °C, jusqu'à ce que ce soit bien chaud partout."],
    "Une moutarde à l'ancienne donne une sauce encore plus gourmande.", ['américain', 'air fryer', 'poêle', 'batch']),

  R('W51', 'Pommes de terre farcies façon lasagne', 'dinner', '🥔', 15, 50,
    [['pdt', 350], ['boeuf', 140], ['tomates_conc', 150], ['concentre', 10], ['oignon', 40], ['ail', 1], ['epices', 2], ['cottage', 80], ['emmental', 20], ['salade', 40], ['huile', 3]],
    ["Lave les pommes de terre, pique-les plusieurs fois à la fourchette et frotte-les avec un peu d'huile et de sel. Fais-les cuire 40 à 45 minutes à l'air fryer à 200 °C, en les retournant à mi-cuisson, jusqu'à ce qu'une lame s'enfonce sans résistance.",
     "Pendant ce temps, hache l'oignon et fais-le revenir 3 minutes à la poêle avec le reste de l'huile. Ajoute le bœuf et fais-le dorer 4 minutes en l'émiettant, puis l'ail écrasé, l'origan, le concentré et les tomates. Laisse mijoter 8 minutes.",
     "Coupe les pommes de terre en deux dans la longueur et écrase un peu la chair à la fourchette. Garnis-les de bolognaise, puis de cottage cheese et d'emmental.",
     "Remets-les 4 minutes à l'air fryer à 200 °C pour faire fondre et dorer le fromage.",
     "Mise en boîtes : les pommes de terre farcies, la salade à part.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes, ou 6 minutes à l'air fryer à 180 °C pour retrouver le gratiné. Sers avec la salade."],
    "Choisis de grosses pommes de terre de même taille : elles cuisent en même temps.", ['américain', 'gourmand', 'air fryer', 'poêle', 'batch']),

  R('W52', 'Bowl elote : crevettes, maïs grillé, quinoa et feta', 'lunch', '🌽', 15, 15,
    [['crevettes', 150], ['quinoa', 70], ['mais', 100], ['tomates_cerise', 80], ['feta', 30], ['avocat', 40], ['oignon', 20], ['herbes', 3], ['yaourt_grec', 40], ['citron_vert', 15], ['epices', 2], ['huile', 5]],
    [CREVETTES_VEILLE,
     QUINOA_AC,
     "Égoutte le maïs, sèche-le et fais-le griller 5 à 6 minutes à la poêle bien chaude, sans matière grasse, jusqu'à ce qu'il noircisse par endroits. Réserve-le.",
     "Dans la même poêle, fais cuire les crevettes 3 minutes avec l'huile, le paprika fumé et une pincée de piment, jusqu'à ce qu'elles soient bien roses.",
     "Prépare la sauce : le yaourt, la moitié du jus de citron vert, une pincée de paprika et de sel. Coupe les tomates cerises en deux et l'oignon rouge en fines lamelles.",
     "Mise en boîtes : le quinoa, le maïs, les tomates et les crevettes ensemble ; la feta émiettée, la coriandre et la sauce à part. Avec des crevettes, il se garde 2 jours.",
     "Au moment de manger : froid, ou réchauffé 1 minute 30 au micro-ondes. Ajoute l'avocat coupé en dés, la feta, la coriandre, la sauce et le reste du citron vert."],
    "Le maïs doit vraiment noircir à la poêle : c'est ce goût grillé qui fait l'elote.", ['mexicain', 'poêle', 'autocuiseur', 'batch', 'froid']),

  R('W53', 'Salade dense aux haricots, boulgour, feta et concombre', 'lunch', '🥗', 15, 9,
    [['haricots_blancs', 150], ['pois_chiches', 100], ['boulghour', 50], ['feta', 40], ['concombre', 100], ['tomates_cerise', 100], ['oignon', 20], ['herbes', 5], ['citron', 15], ['huile', 10], ['epices', 1]],
    [BOULGOUR_AC + " Laisse-le refroidir.",
     "Rince et égoutte les haricots blancs et les pois chiches. Coupe le concombre et les tomates cerises en petits dés, et hache finement l'oignon rouge, le persil et la menthe.",
     "Prépare la sauce : l'huile d'olive, le jus de citron, l'origan, du sel et du poivre.",
     "Mélange le boulgour froid, les haricots, les pois chiches, les légumes, les herbes et la sauce, puis ajoute la feta émiettée.",
     "Mise en boîtes : la salade toute prête, au frigo. Elle se garde 4 jours et devient même meilleure le lendemain.",
     "Au moment de manger : sors-la du frigo 10 minutes avant, et mélange-la bien."],
    "« Dense » parce que chaque bouchée est pleine : beaucoup de légumineuses, peu de feuilles.", ['méditerranéen', 'végé', 'autocuiseur', 'batch', 'froid']),

  R('W54', 'Aubergines laquées soja-miel, tofu croustillant et quinoa', 'dinner', '🍆', 15, 20,
    [['tofu', 180], ['aubergine', 200], ['quinoa', 70], ['fecule', 8], ['soja', 20], ['miel', 10], ['ail', 1], ['gingembre', 5], ['sesame', 5], ['huile', 10]],
    ["Égoutte le tofu, presse-le 10 minutes entre deux torchons sous une casserole, puis coupe-le en cubes de 2 cm. Mélange-les avec la fécule et la moitié de l'huile, et fais-les cuire 14 à 15 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson, jusqu'à ce qu'ils soient bien dorés.",
     "Coupe l'aubergine en cubes de 2 cm, mélange-les avec le reste de l'huile et fais-les cuire 15 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson, jusqu'à ce qu'elles soient fondantes.",
     QUINOA_AC,
     "Dans la poêle, mélange la sauce soja, le miel, l'ail écrasé, le gingembre râpé et 3 cuillères à soupe d'eau. Fais réduire 2 minutes à feu moyen, jusqu'à ce que la sauce soit sirupeuse.",
     "Ajoute l'aubergine et le tofu, et remue 1 minute pour bien les laquer. Parsème de graines de sésame.",
     "Mise en boîtes : le quinoa et les aubergines laquées au tofu ensemble.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes, ou 5 minutes à l'air fryer à 180 °C pour que le tofu redevienne croustillant."],
    "Bien presser le tofu, c'est le secret d'une croûte croustillante.", ['asiatique', 'végé', 'air fryer', 'autocuiseur', 'batch']),

  R('W55', 'Wrap plié croustillant au thon, cheddar et avocat', 'lunch', '🌯', 15, 6,
    [['thon', 120], ['tortilla', 120], ['cheddar', 30], ['yaourt_grec', 40], ['moutarde', 5], ['mais', 50], ['oignon', 15], ['tomate', 60], ['salade', 30], ['avocat', 50], ['epices', 1]],
    ["Mélange le thon égoutté avec le yaourt, la moutarde, du sel et du poivre. Égoutte le maïs, coupe la tomate en fines rondelles et l'oignon rouge en lamelles.",
     "Mise en boîtes : la garniture au thon, le maïs avec l'oignon, la tomate et la salade dans des boîtes séparées, les wraps et le cheddar à part. Le thon se garde 3 jours au frigo.",
     "Au moment de manger, pose un wrap à plat et fais une entaille du centre jusqu'au bord, vers le bas. Garnis chaque quart : le thon en haut à gauche, le cheddar et l'avocat en tranches en haut à droite, le maïs et l'oignon en bas à droite, la tomate et la salade en bas à gauche.",
     "Replie le quart du bas à gauche sur celui du haut, puis continue dans le sens des aiguilles d'une montre, jusqu'à obtenir un triangle.",
     "Fais-le dorer 2 à 3 minutes par face à la poêle sans matière grasse, en appuyant avec une spatule, jusqu'à ce que le cheddar fonde."],
    "Le pliage en triangle garde chaque garniture à sa place : chaque bouchée a un goût différent.", ['américain', 'poêle', 'batch', 'assemblage']),
  // ════ Lots 2 et 3 : 20 plats de poulet et de bœuf ════
  R('W56', 'Pâtes crémeuses épicées au poulet, sauce tomate-sriracha', 'dinner', '🌶️', 10, 18,
    [['poulet', 150], ['pates', 90], ['oignon', 40], ['ail', 1], ['concentre', 20], ['sriracha', 15], ['miel', 5], ['soja', 10], ['creme', 25], ['parmesan', 10], ['huile', 5]],
    ["Coupe le poulet en dés de 2 cm et fais-le cuire 6 à 7 minutes à la poêle avec l'huile, jusqu'à ce qu'il ne soit plus rose au centre. Réserve-le.",
     "Dans la même poêle, fais revenir l'oignon haché 3 minutes, puis l'ail écrasé 1 minute.",
     "Ajoute le concentré de tomate, la sriracha, le miel, la sauce soja et 100 ml d'eau par portion. Laisse mijoter 3 minutes, jusqu'à ce que la sauce épaississe.",
     PATES_AC,
     "Hors du feu, ajoute la crème fraîche, le parmesan et l'eau de cuisson gardée à la sauce, puis les pâtes et le poulet. Mélange bien : la sauce devient orange et onctueuse.",
     "Mise en boîtes : les pâtes, au frigo dès qu'elles ont tiédi.",
     REWARM],
    "Ajuste la sriracha à ton goût : la crème adoucit beaucoup le piquant.", ['coréen', 'gourmand', 'poêle', 'autocuiseur', 'batch']),

  R('W57', 'Pâtes cajun au poulet et aux poivrons', 'dinner', '🔥', 10, 18,
    [['poulet', 150], ['pates', 90], ['poivron', 80], ['oignon', 40], ['ail', 1], ['epices', 4], ['tomates_conc', 100], ['lait', 100], ['fecule', 4], ['emmental', 25], ['huile', 5]],
    ["Coupe le poulet en dés de 2 cm et mélange-les avec les épices cajun : paprika fumé, ail en poudre, origan, thym, une pincée de piment et de sel.",
     "Fais cuire le poulet 6 à 7 minutes à la poêle avec l'huile. Ajoute le poivron en lanières et l'oignon émincé, et laisse cuire 4 minutes de plus.",
     "Ajoute l'ail écrasé et les tomates, et laisse mijoter 3 minutes. Délaye la fécule dans le lait froid, verse-le dans la poêle et remue 2 minutes, jusqu'à ce que la sauce épaississe. Hors du feu, ajoute l'emmental.",
     PATES_AC + " Mélange-les à la sauce avec l'eau de cuisson gardée.",
     "Mise en boîtes : les pâtes cajun, au frigo dès qu'elles ont tiédi.",
     REWARM],
    "Le paprika fumé fait tout le goût cajun : n'hésite pas sur la dose.", ['cajun', 'gourmand', 'poêle', 'autocuiseur', 'batch']),

  R('W58', 'Pâtes fajitas au poulet, sauce cheddar', 'dinner', '🫑', 10, 18,
    [['poulet', 150], ['pates', 90], ['poivron', 120], ['oignon', 60], ['epices', 4], ['concentre', 15], ['lait', 80], ['cheddar', 30], ['citron_vert', 10], ['huile', 5]],
    ["Coupe le poulet en lanières et mélange-les avec les épices : paprika, cumin, origan, ail en poudre et une pincée de sel.",
     "Fais cuire le poulet 5 minutes à la poêle bien chaude avec l'huile, puis ajoute les poivrons et l'oignon en lanières et laisse cuire 5 minutes à feu vif, jusqu'à ce qu'ils soient dorés par endroits mais encore croquants.",
     "Ajoute le concentré de tomate et le lait, et remue 2 minutes. Hors du feu, ajoute le cheddar en morceaux et remue jusqu'à ce qu'il fonde, puis le jus de citron vert.",
     PATES_AC + " Mélange-les à la sauce avec l'eau de cuisson gardée.",
     "Mise en boîtes : les pâtes fajitas, au frigo dès qu'elles ont tiédi.",
     REWARM],
    "Les poivrons doivent griller à feu vif : c'est ce goût un peu brûlé qui rappelle les fajitas.", ['mexicain', 'gourmand', 'poêle', 'autocuiseur', 'batch']),

  R('W59', 'Pâtes au poulet, pesto et tomates cerises', 'dinner', '🌿', 10, 15,
    [['poulet', 150], ['pates', 90], ['pesto', 20], ['yaourt_grec', 40], ['tomates_cerise', 150], ['epinards', 50], ['ail', 1], ['parmesan', 10], ['huile', 3]],
    ["Coupe le poulet en dés de 2 cm et fais-le cuire 6 à 7 minutes à la poêle avec l'huile, jusqu'à ce qu'il soit doré.",
     "Ajoute les tomates cerises coupées en deux, l'ail écrasé et les épinards, et laisse cuire 3 minutes, jusqu'à ce que les tomates commencent à fondre.",
     PATES_AC,
     "Hors du feu, mélange le pesto, le yaourt et l'eau de cuisson gardée, puis ajoute les pâtes, le poulet et les tomates. Le yaourt rend le pesto crémeux, sans crème.",
     "Mise en boîtes : les pâtes, avec le parmesan dans un petit pot.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes à puissance moyenne avec 2 cuillères à soupe d'eau, en remuant à mi-temps. Ajoute le parmesan."],
    "Ajoute le pesto hors du feu : chauffé, le basilic perd sa couleur et son parfum.", ['italien', 'poêle', 'autocuiseur', 'batch']),

  R('W60', 'Paprikás de poulet sur nouilles aux œufs', 'dinner', '🇭🇺', 10, 20,
    [['haut_cuisse', 170], ['nouilles_oeufs', 90], ['poivron', 150], ['oignon', 80], ['ail', 1], ['epices', 6], ['tomates_conc', 100], ['yaourt_grec', 60], ['huile', 5]],
    ["Coupe le poulet en morceaux de 3 cm, l'oignon et les poivrons en lanières.",
     "Dans l'autocuiseur en mode dorer, fais revenir l'oignon 4 minutes dans l'huile, jusqu'à ce qu'il soit fondant. Ajoute le poulet et fais-le colorer 3 minutes.",
     "Arrête le mode dorer, ajoute l'ail et le paprika doux, et mélange 30 secondes : hors du feu, le paprika ne brûle pas. Ajoute les poivrons, les tomates, 100 ml d'eau par portion et une pincée de sel.",
     "Ferme et laisse cuire 8 minutes sous pression, puis fais tomber la pression. Laisse réduire 3 minutes en mode dorer si la sauce est trop liquide.",
     NOUILLES_AC,
     "Hors du feu, quand le paprikás a un peu tiédi, ajoute le yaourt et mélange : il remplace la crème aigre hongroise.",
     "Mise en boîtes : les nouilles, avec le paprikás par-dessus.",
     REWARM],
    "Le paprika doit être doux et généreux : c'est lui qui donne la couleur et le goût.", ['hongrois', 'autocuiseur', 'batch']),

  R('W61', 'Stroganoff de bœuf haché aux champignons, nouilles aux œufs', 'dinner', '🍄', 10, 18,
    [['boeuf', 150], ['champignons', 150], ['oignon', 60], ['ail', 1], ['moutarde', 10], ['epices', 2], ['soja', 5], ['creme', 25], ['yaourt_grec', 40], ['nouilles_oeufs', 90], ['huile', 5]],
    ["Émince l'oignon et les champignons.",
     "Fais revenir l'oignon 3 minutes à la poêle avec l'huile, puis ajoute le bœuf et fais-le dorer 4 minutes en l'émiettant.",
     "Ajoute les champignons et laisse cuire 5 minutes, jusqu'à ce qu'ils aient rendu leur eau et qu'elle se soit évaporée. Ajoute l'ail écrasé, le paprika, la moutarde, la sauce soja et 80 ml d'eau par portion, et laisse mijoter 3 minutes.",
     "Hors du feu, ajoute la crème et le yaourt, et mélange : la sauce devient crémeuse.",
     NOUILLES_AC,
     "Mise en boîtes : les nouilles, avec le stroganoff par-dessus.",
     REWARM],
    "Laisse bien dorer les champignons avant d'ajouter la sauce : c'est là que se fait le goût.", ['russe', 'poêle', 'autocuiseur', 'batch']),

  R('W62', 'Penne sauce tomate crémeuse et boulettes de bœuf', 'dinner', '🍝', 15, 18,
    [['boeuf', 150], ['parmesan', 15], ['oignon', 40], ['ail', 1], ['epices', 2], ['tomates_conc', 200], ['concentre', 15], ['creme', 20], ['pates', 90], ['huile', 5]],
    ["Mélange le bœuf avec la moitié du parmesan, un quart de l'oignon râpé, l'origan et une pincée de sel. Forme des boulettes de la taille d'une noix.",
     "Fais-les cuire 9 à 10 minutes à l'air fryer à 200 °C, en secouant le panier à mi-cuisson.",
     "Pendant ce temps, fais revenir le reste de l'oignon haché 3 minutes à la poêle avec l'huile, puis l'ail 1 minute. Ajoute le concentré, les tomates et une pincée de piment, et laisse mijoter 8 minutes.",
     "Hors du feu, ajoute la crème : la sauce devient rose et onctueuse, comme une sauce « alla vodka », sans vodka. Ajoute les boulettes.",
     PATES_AC + " Mélange-les à la sauce avec l'eau de cuisson gardée.",
     "Mise en boîtes : les penne et les boulettes, le reste du parmesan dans un petit pot.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 2 cuillères à soupe d'eau, en remuant à mi-temps. Ajoute le parmesan."],
    "Les boulettes cuites à l'air fryer restent bien rondes et ne rendent pas de gras dans la sauce.", ['italien', 'gourmand', 'air fryer', 'poêle', 'autocuiseur', 'batch']),

  R('W63', 'Poulet crémeux aux champignons, purée et haricots verts', 'dinner', '🥘', 15, 20,
    [['poulet', 160], ['champignons', 150], ['oignon', 40], ['ail', 1], ['moutarde', 5], ['creme', 25], ['herbes', 2], ['pdt', 300], ['lait', 60], ['haricots_verts', 120], ['huile', 5]],
    ["Épluche les pommes de terre, coupe-les en gros morceaux et mets-les dans l'autocuiseur avec 250 ml d'eau et une pincée de sel. Ferme et laisse cuire 8 minutes sous pression, puis fais tomber la pression.",
     "Égoutte-les et écrase-les à la fourchette ou au presse-purée avec le lait chaud, du sel et du poivre.",
     "Coupe le poulet en morceaux et fais-le cuire 6 minutes à la poêle avec l'huile. Ajoute l'oignon haché et les champignons émincés, et laisse cuire 5 minutes, jusqu'à ce qu'ils soient dorés.",
     "Ajoute l'ail, le thym, la moutarde et 60 ml d'eau par portion, laisse mijoter 2 minutes, puis ajoute la crème hors du feu.",
     "Fais cuire les haricots verts 6 minutes dans la poêle rincée avec un fond d'eau, à couvert.",
     "Mise en boîtes : la purée, le poulet aux champignons et les haricots verts.",
     REWARM],
    "Un peu d'eau ou de lait au réchauffage, et la purée redevient aussi souple que le premier jour.", ['français', 'autocuiseur', 'poêle', 'batch']),

  R('W64', 'Poulet à l\'ail et aux herbes, grenailles et courgettes rôties', 'dinner', '🧄', 10, 25,
    [['haut_cuisse', 170], ['pdt', 250], ['courgette', 150], ['ail', 2], ['herbes', 5], ['citron', 10], ['epices', 1], ['huile', 10]],
    ["Coupe les pommes de terre en deux avec la peau et la courgette en demi-rondelles épaisses. Mélange-les avec la moitié de l'huile, les herbes de Provence et une pincée de sel.",
     "Fais cuire les pommes de terre 12 minutes à l'air fryer à 200 °C, puis ajoute la courgette et prolonge de 10 minutes, en secouant le panier à mi-cuisson.",
     "Pendant ce temps, fais cuire le poulet en morceaux 8 minutes à la poêle avec le reste de l'huile, jusqu'à ce qu'il soit bien doré.",
     "Baisse le feu, ajoute l'ail écrasé, le persil haché et le jus de citron, et remue 1 minute sans laisser brûler l'ail.",
     "Mise en boîtes : le poulet sur les pommes de terre et les courgettes.",
     "Au moment de manger : réchauffe 5 minutes à l'air fryer à 180 °C pour retrouver le croustillant, ou 3 minutes au micro-ondes."],
    "Ajoute l'ail en fin de cuisson seulement : il parfume sans brûler.", ['français', 'air fryer', 'poêle', 'batch']),

  R('W65', 'Bowl de poulet buffalo, pommes de terre et sauce yaourt', 'dinner', '🍗', 15, 22,
    [['poulet', 160], ['pdt', 250], ['sriracha', 15], ['vinaigre_cidre', 5], ['miel', 3], ['huile', 8], ['epices', 2], ['yaourt_grec', 80], ['herbes', 3], ['ail', 1], ['carotte', 60], ['concombre', 60]],
    ["Coupe les pommes de terre en cubes de 2 cm avec la peau, mélange-les avec 5 ml d'huile, le paprika et une pincée de sel, et fais-les cuire 20 minutes à l'air fryer à 200 °C, en secouant toutes les 7 minutes.",
     "Coupe le poulet en morceaux de 3 cm et fais-le cuire 6 à 7 minutes à la poêle avec le reste de l'huile.",
     "Mélange la sriracha, le vinaigre de cidre et le miel, verse sur le poulet et remue 1 minute : c'est la sauce buffalo, piquante et acidulée.",
     "Prépare la sauce : le yaourt, la ciboulette ciselée, une demi-gousse d'ail écrasée, du sel et du poivre. Coupe la carotte et le concombre en bâtonnets.",
     "Mise en boîtes : les pommes de terre et le poulet buffalo ensemble, les bâtonnets et la sauce à part.",
     "Au moment de manger : réchauffe le poulet et les pommes de terre 4 minutes à l'air fryer à 180 °C, ou 3 minutes au micro-ondes. Ajoute la sauce froide et les bâtonnets."],
    "La sauce au yaourt bien froide calme le piquant du buffalo.", ['américain', 'air fryer', 'poêle', 'batch']),

  R('W66', 'Poêlée de bœuf, pommes de terre et poivrons, œuf au plat', 'dinner', '🍳', 10, 22,
    [['boeuf', 150], ['pdt', 250], ['poivron', 120], ['oignon', 60], ['ail', 1], ['epices', 3], ['oeuf', 1], ['herbes', 2], ['huile', 8]],
    ["Coupe les pommes de terre en dés de 1,5 cm avec la peau, mélange-les avec 5 ml d'huile et une pincée de sel, et fais-les cuire 18 minutes à l'air fryer à 200 °C, en secouant toutes les 6 minutes.",
     "Pendant ce temps, fais revenir l'oignon et les poivrons en dés 5 minutes à la poêle avec le reste de l'huile. Ajoute le bœuf et fais-le dorer 5 minutes en l'émiettant, avec l'ail, le paprika fumé, le cumin et une pincée de sel.",
     "Ajoute les pommes de terre croustillantes et mélange 1 minute, puis le persil haché.",
     "Mise en boîtes : la poêlée, au frigo dès qu'elle a tiédi.",
     "Au moment de manger : réchauffe la poêlée 5 minutes à la poêle à feu moyen, ou 3 minutes au micro-ondes. Pendant ce temps, fais cuire l'œuf au plat 3 minutes à la poêle et pose-le dessus : le jaune coulant fait la sauce."],
    "L'œuf se cuit au dernier moment : 3 minutes, et le plat devient un vrai brunch.", ['américain', 'air fryer', 'poêle', 'batch']),

  R('W67', 'Picadillo de bœuf aux pommes de terre', 'dinner', '🇨🇺', 10, 20,
    [['boeuf', 150], ['pdt', 200], ['tomates_conc', 150], ['concentre', 10], ['oignon', 50], ['poivron', 60], ['ail', 1], ['olives', 20], ['epices', 2], ['vinaigre_cidre', 5], ['huile', 5]],
    ["Épluche les pommes de terre et coupe-les en dés de 1,5 cm. Hache l'oignon et le poivron, coupe les olives en rondelles.",
     "Dans l'autocuiseur en mode dorer, fais revenir l'oignon et le poivron 3 minutes dans l'huile, puis ajoute le bœuf et fais-le dorer 4 minutes en l'émiettant.",
     "Ajoute l'ail, le cumin, l'origan, le concentré, les tomates, les pommes de terre, les olives, le vinaigre et 60 ml d'eau par portion. Mélange.",
     "Ferme et laisse cuire 5 minutes sous pression, puis fais tomber la pression. Les pommes de terre doivent être tendres mais garder leur forme.",
     "Mise en boîtes : le picadillo, au frigo dès qu'il a tiédi.",
     REWARM],
    "Les olives et le vinaigre donnent ce petit goût aigre-doux typique de Cuba.", ['cubain', 'autocuiseur', 'batch']),

  R('W68', 'Keema aloo : bœuf haché, pommes de terre et petits pois', 'dinner', '🍛', 10, 20,
    [['boeuf', 150], ['pdt', 200], ['petits_pois', 80], ['oignon', 60], ['ail', 1], ['gingembre', 5], ['tomates_conc', 120], ['epices', 5], ['yaourt_grec', 40], ['herbes', 3], ['huile', 5]],
    ["Épluche les pommes de terre et coupe-les en dés de 1,5 cm. Hache l'oignon, écrase l'ail et râpe le gingembre.",
     "Dans l'autocuiseur en mode dorer, fais revenir l'oignon 4 minutes dans l'huile, puis l'ail, le gingembre, le garam masala, le cumin, le curcuma et une pincée de piment 1 minute.",
     "Ajoute le bœuf et fais-le dorer 4 minutes en l'émiettant, puis les tomates, les pommes de terre et 80 ml d'eau par portion.",
     "Ferme et laisse cuire 5 minutes sous pression, puis fais tomber la pression. Ajoute les petits pois et laisse-les cuire 3 minutes en mode dorer.",
     "Mise en boîtes : le keema, le yaourt et la coriandre dans un petit pot.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 2 cuillères à soupe d'eau, en remuant à mi-temps. Ajoute le yaourt froid et la coriandre."],
    "Encore meilleur le lendemain : les épices ont le temps de se marier.", ['indien', 'autocuiseur', 'batch']),

  R('W69', 'Bowl de poulet à la marocaine, semoule et chou-fleur rôti', 'dinner', '🥙', 15, 20,
    [['poulet', 160], ['semoule', 80], ['chou_fleur', 150], ['pois_chiches', 60], ['oignon', 30], ['epices', 4], ['miel', 3], ['citron', 10], ['yaourt_grec', 50], ['herbes', 3], ['huile', 8]],
    ["Coupe le poulet en morceaux de 3 cm et mélange-les avec la moitié des épices (cumin, paprika, cannelle, gingembre en poudre), le miel, la moitié de l'huile et une pincée de sel.",
     "Mélange le chou-fleur et les pois chiches égouttés avec le reste des épices et de l'huile. Fais-les cuire 15 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson, puis réserve.",
     "Fais cuire le poulet 12 à 14 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson, jusqu'à ce qu'il soit doré.",
     "Verse la semoule dans un saladier avec le même volume d'eau bouillante, une pincée de sel et un filet de jus de citron. Couvre 5 minutes, puis égrène-la à la fourchette.",
     "Prépare la sauce : le yaourt, la menthe ciselée, le reste du citron et une pincée de sel. Émince l'oignon rouge très finement.",
     "Mise en boîtes : la semoule, le poulet, le chou-fleur et les pois chiches ensemble ; la sauce et l'oignon à part.",
     "Au moment de manger : réchauffe 3 minutes au micro-ondes avec 1 cuillère à soupe d'eau. Ajoute la sauce et l'oignon."],
    "Le chou-fleur rôti aux épices devient presque sucré : c'est lui la vedette du bowl.", ['marocain', 'air fryer', 'batch']),

  R('W70', 'Poulet shawarma, boulgour et sauce tahini', 'dinner', '🌯', 15, 20,
    [['poulet', 160], ['boulghour', 75], ['epices', 4], ['citron', 15], ['ail', 1], ['huile', 8], ['tahini', 15], ['yaourt_grec', 40], ['tomate', 80], ['concombre', 80], ['oignon', 20], ['herbes', 3]],
    ["Coupe le poulet en lanières et mélange-les avec le cumin, le paprika, une pincée de cannelle et de curcuma, la moitié du citron, l'ail écrasé, l'huile et une pincée de sel. Laisse mariner 15 minutes, ou toute la nuit au frigo.",
     "Fais-le cuire 12 à 14 minutes à l'air fryer à 200 °C, en secouant à mi-cuisson, jusqu'à ce que les bords soient bien grillés.",
     BOULGOUR_AC,
     "Prépare la sauce : le tahini, le yaourt, le reste du citron, 2 cuillères à soupe d'eau et une pincée de sel, bien mélangés jusqu'à ce que ce soit lisse.",
     "Coupe la tomate et le concombre en dés, l'oignon rouge en fines lamelles, et hache le persil.",
     "Mise en boîtes : le boulgour et le poulet ensemble, les crudités et la sauce à part.",
     "Au moment de manger : réchauffe le boulgour et le poulet 3 minutes au micro-ondes. Ajoute les crudités et la sauce tahini."],
    "La sauce tahini épaissit au frigo : détends-la avec une cuillère d'eau.", ['libanais', 'air fryer', 'autocuiseur', 'batch']),

  R('W71', 'Poêlée épicée de bœuf et quinoa, haricots rouges et maïs', 'dinner', '🌶️', 10, 18,
    [['boeuf', 150], ['quinoa', 70], ['haricots_rouges', 80], ['mais', 60], ['poivron', 80], ['oignon', 40], ['ail', 1], ['tomates_conc', 100], ['epices', 4], ['citron_vert', 10], ['herbes', 3], ['huile', 5]],
    [QUINOA_AC,
     "Fais revenir l'oignon et le poivron en dés 4 minutes à la poêle avec l'huile. Ajoute le bœuf et fais-le dorer 5 minutes en l'émiettant.",
     "Ajoute l'ail, le cumin, le paprika fumé, une pincée de piment, les tomates, les haricots rouges rincés et le maïs égoutté. Laisse mijoter 5 minutes.",
     "Ajoute le quinoa et mélange, puis le jus de citron vert et la coriandre hachée.",
     "Mise en boîtes : la poêlée, au frigo dès qu'elle a tiédi.",
     REWARM],
    "Tout le chili dans une seule poêle, avec le quinoa qui boit la sauce.", ['mexicain', 'poêle', 'autocuiseur', 'batch']),

  R('W72', 'Curry de poulet aux pois chiches et naans au fromage', 'dinner', '🫓', 20, 25,
    [['poulet', 150], ['pois_chiches', 80], ['oignon', 50], ['ail', 1], ['gingembre', 5], ['epices', 5], ['tomates_conc', 150], ['epinards', 50], ['yaourt_grec', 100], ['farine', 70], ['levure', 2], ['emmental', 20], ['huile', 5]],
    ["Pâte à naans : mélange la farine, la levure, une pincée de sel et la moitié du yaourt, puis pétris 2 minutes jusqu'à obtenir une boule souple. Laisse reposer 15 minutes sous un torchon.",
     "Pendant ce temps, fais revenir l'oignon haché 4 minutes à la poêle avec l'huile, puis l'ail, le gingembre, le garam masala, le curry et le curcuma 1 minute.",
     "Ajoute le poulet en dés et fais-le colorer 3 minutes, puis les tomates, les pois chiches égouttés et 60 ml d'eau par portion. Laisse mijoter 10 minutes, ajoute les épinards 2 minutes, puis, hors du feu, le reste du yaourt.",
     "Partage la pâte en deux par portion, aplatis chaque morceau, pose l'emmental au centre, referme et aplatis de nouveau en galette de 5 mm.",
     "Fais cuire les naans 2 minutes par face dans la poêle rincée, sans matière grasse, à feu moyen, jusqu'à ce qu'ils gonflent et dorent par endroits.",
     "Mise en boîtes : le curry, les naans emballés à part.",
     "Au moment de manger : réchauffe le curry 3 minutes au micro-ondes en remuant à mi-temps, et les naans 2 minutes à l'air fryer à 180 °C."],
    "La pâte farine-yaourt ne demande ni levure de boulanger ni four : les naans gonflent à la poêle.", ['indien', 'gourmand', 'poêle', 'batch']),

  R('W73', 'Burritos de bœuf miel et paprika fumé', 'dinner', '🌯', 20, 20,
    [['boeuf', 150], ['haricots_rouges', 100], ['oignon', 40], ['poivron', 60], ['concentre', 15], ['miel', 6], ['epices', 4], ['cheddar', 25], ['tortilla', 120], ['yaourt_grec', 30], ['huile', 3]],
    ["Fais revenir l'oignon et le poivron en dés 4 minutes à la poêle avec l'huile, puis ajoute le bœuf et fais-le dorer 5 minutes en l'émiettant.",
     "Ajoute le paprika fumé, le cumin, l'ail en poudre, le concentré, le miel, les haricots rouges rincés et 50 ml d'eau par portion. Laisse réduire 3 minutes, jusqu'à ce que ce soit bien enrobé.",
     "Sur chaque wrap, dépose la garniture au bœuf et aux haricots, puis le cheddar. Replie les côtés, puis roule bien serré.",
     "Fais dorer les burritos 2 minutes par face à la poêle sans matière grasse, côté soudure en premier pour qu'ils restent fermés.",
     "Mise en boîtes : les burritos emballés un par un dans du film ou du papier aluminium, le yaourt dans un petit pot. Ils se congèlent très bien.",
     "Au moment de manger : réchauffe 2 minutes au micro-ondes, puis 3 minutes à l'air fryer à 200 °C pour qu'ils redeviennent croustillants. Si le burrito sort du congélateur, laisse-le décongeler une nuit au frigo. Trempe dans le yaourt."],
    "Bien serrés et dorés côté soudure, les burritos ne s'ouvrent pas au réchauffage.", ['mexicain', 'gourmand', 'poêle', 'batch']),

  R('W74', 'Philly cheesesteak : bœuf, poivrons et cheddar fondu', 'dinner', '🥖', 15, 12,
    [['boeuf_emince', 150], ['baguette', 130], ['poivron', 100], ['oignon', 80], ['champignons', 60], ['cheddar', 30], ['soja', 5], ['epices', 1], ['huile', 5]],
    ["Mets le bœuf 30 minutes au congélateur, puis taille-le en tranches très fines : il se coupe beaucoup plus facilement à moitié congelé.",
     "Fais revenir l'oignon, le poivron et les champignons émincés 8 minutes à la poêle avec l'huile, jusqu'à ce qu'ils soient fondants et dorés.",
     "Monte le feu, ajoute le bœuf, la sauce soja et du poivre, et fais-le sauter 2 minutes seulement, pour qu'il reste tendre.",
     "Mise en boîtes : la garniture au bœuf, le cheddar et la baguette à part.",
     "Au moment de manger : réchauffe la garniture 2 minutes à la poêle, pose le cheddar dessus et couvre 1 minute pour qu'il fonde. Pendant ce temps, ouvre la baguette et fais-la griller 3 minutes à l'air fryer à 200 °C. Garnis-la."],
    "Le bœuf ne doit sauter que 2 minutes : trop cuit, il devient sec.", ['américain', 'gourmand', 'poêle', 'batch', 'assemblage']),

  R('W75', 'Mafé de bœuf, sauce cacahuète et tomate', 'dinner', '🥜', 15, 30,
    [['boeuf_emince', 160], ['beurre_cacahuete', 25], ['oignon', 60], ['ail', 1], ['gingembre', 5], ['concentre', 15], ['tomates_conc', 120], ['carotte', 80], ['patate_douce', 100], ['epices', 2], ['riz', 90], ['huile', 5]],
    ["Coupe le bœuf en cubes de 3 cm, la carotte en rondelles épaisses et la patate douce en gros cubes. Hache l'oignon, écrase l'ail et râpe le gingembre.",
     "Dans l'autocuiseur en mode dorer, fais dorer le bœuf 4 minutes dans l'huile, puis ajoute l'oignon 3 minutes, l'ail et le gingembre 1 minute.",
     "Délaye le beurre de cacahuète et le concentré dans 150 ml d'eau chaude par portion. Verse-les dans la cuve avec les tomates, la carotte, la patate douce, une pincée de piment et de sel.",
     "Ferme et laisse cuire 25 minutes sous pression, puis laisse la pression retomber seule. La viande doit être fondante et la sauce épaisse ; laisse réduire quelques minutes en mode dorer si besoin.",
     RIZ_AC,
     "Mise en boîtes : le riz et le mafé à part ou ensemble. Il se congèle très bien.",
     REWARM],
    "Un beurre de cacahuète sans sucre ajouté donne le vrai goût du mafé.", ['sénégalais', 'autocuiseur', 'batch']),
];