// Plats du monde — matériel : plaques, autocuiseur (AC), air fryer (AF). Pas de four.
// pairs : accompagnements air fryer suggérés.
const R = (id, name, cat, emoji, prep, cook, ings, steps, tip, tags, extra = {}) =>
  ({ id, name, cat, emoji, prep, cook, ings, steps, tip, tags, batch: true, ...extra });

exports.mains = [
  // ════ Série 1 ════
  R('W01', 'Curry de poulet à l\'aubergine et au lait de coco', 'dinner', '🍛', 10, 15,
    [['poulet', 170], ['aubergine', 120], ['poivron', 60], ['oignon', 40], ['ail', 1], ['gingembre', 5], ['epices', 6], ['lait_coco', 100], ['soja', 10], ['huile', 5], ['herbes', 3], ['riz', 90]],
    ['AC mode dorer : 2 min la pâte de curry avec un fond de lait de coco.', 'Ajouter le poulet en dés, l\'aubergine en cubes, le poivron, le reste du lait de coco et le nuoc mam.', 'Fermer, 8 min sous pression, dépressuriser rapidement.', 'Basilic thaï au moment de servir. Riz jasmin à part (casserole ou AC).'],
    'L\'aubergine boit la sauce et devient fondante : encore meilleur à J+1.', ['thaï', 'autocuiseur', 'batch'], { pairs: ['SA12'] }),
  R('W02', 'Bol de poulet à la vietnamienne', 'lunch', '🥢', 15, 14,
    [['haut_cuisse', 170], ['riz', 90], ['carotte', 60], ['concombre', 80], ['salade', 40], ['cacahuetes', 15], ['ail', 1], ['citron_vert', 20], ['soja', 15], ['miel', 8], ['huile', 5], ['herbes', 3]],
    ['Mariner le poulet : citronnelle hachée, ail, nuoc mam, miel (15 min ou la veille).', 'AF 200°C 12-14 min en retournant à mi-cuisson, puis trancher.', 'Vermicelles : 4 min dans l\'eau bouillante, rincer à froid.', 'Sauce : nuoc mam + citron vert + 1 c.à.c miel + 3 c.à.s d\'eau.', 'Boîtes : vermicelles, crudités, poulet, cacahuètes ; sauce dans un petit pot.'],
    'Bowl froid : aucun réchauffage, parfait au bureau.', ['vietnamien', 'air fryer', 'batch', 'froid']),
  R('W03', 'Gyudon : bœuf et oignons au soja', 'dinner', '🍚', 10, 15,
    [['boeuf_emince', 170], ['oignon', 120], ['soja', 20], ['miel', 10], ['vinaigre_cidre', 5], ['gingembre', 5], ['epinards', 80], ['huile', 3], ['oeuf', 1], ['riz', 90]],
    ['Émincer finement le bœuf (plus facile s\'il est un peu congelé) et l\'oignon.', 'Poêle : oignon + 100 ml d\'eau + soja + mirin + gingembre, 6 min.', 'Ajouter le bœuf, 2-3 min seulement.', 'Œuf mollet (6 min 30) et épinards poêlés à côté. Sur le riz.'],
    'Le bœuf finit de cuire au réchauffage : ne le cuis pas trop au départ.', ['japonais', 'poêle', 'batch'], { pairs: ['SA04'] }),
  R('W04', 'Souvlaki de poulet, tzatziki & pita', 'lunch', '🇬🇷', 15, 12,
    [['poulet', 170], ['citron', 15], ['epices', 3], ['ail', 1], ['huile', 8], ['yaourt_grec', 60], ['concombre', 100], ['tomate', 100], ['oignon', 30], ['pita', 140]],
    ['Mariner le poulet en cubes : citron, origan, ail, huile (idéalement la veille).', 'AF 200°C 12 min, secouer à mi-cuisson.', 'Tzatziki : yaourt + concombre râpé essoré + ail.', 'Pita réchauffée 2 min à l\'AF au moment de manger.'],
    'Garde tzatziki et crudités à part : tout reste croquant 3 jours.', ['grec', 'air fryer', 'batch', 'assemblage'], { pairs: ['SA02', 'SA03'] }),
  R('W05', 'Köfte, boulgour pilavı & cacık', 'dinner', '🧆', 15, 15,
    [['boeuf', 160], ['oignon', 40], ['herbes', 10], ['epices', 4], ['boulghour', 70], ['tomates_conc', 80], ['concentre', 10], ['yaourt_grec', 80], ['concombre', 80], ['huile', 5]],
    ['Mélanger bœuf, oignon râpé, persil, cumin, paprika ; former des köfte allongées.', 'AF 200°C 10-12 min.', 'Pendant ce temps, AC : boulgour revenu dans l\'huile + tomates + concentré + 1,5 volume d\'eau, 4 min sous pression.', 'Cacık : yaourt, concombre en dés, menthe séchée.'],
    'Les köfte crues se congèlent à plat : sors-les la veille. Tu peux mettre 1/3 d\'agneau haché pour le goût.', ['turc', 'air fryer', 'autocuiseur', 'batch'], { pairs: ['SA03', 'SA07'] }),
  R('W06', 'Mujaddara au poulet grillé', 'dinner', '🧅', 10, 25,
    [['lentilles_vertes', 70], ['riz', 60], ['oignon', 120], ['epices', 3], ['huile', 10], ['poulet', 130], ['yaourt_grec', 80], ['ail', 1], ['tomate', 80], ['concombre', 80]],
    ['Oignons en fines lamelles + la moitié de l\'huile : AF 180°C 15-18 min en remuant, jusqu\'à doré.', 'AC : lentilles + riz + cumin + reste d\'huile + 2,5 volumes d\'eau, 12 min sous pression.', 'Yaourt à l\'ail, salade tomate-concombre.', 'Oignons croustillants par-dessus au moment de servir.'],
    'L\'un des plats les moins chers de la liste (~1 €), et pourtant très gourmand.', ['libanais', 'végé', 'autocuiseur', 'air fryer', 'batch', 'économique'], { pairs: ['SA03'] }),
  R('W07', 'Tajine de poulet au citron et aux olives', 'dinner', '🍋', 15, 12,
    [['poulet', 170], ['oignon', 60], ['carotte', 100], ['courgette', 100], ['olives', 20], ['citron', 20], ['epices', 3], ['huile', 5], ['semoule', 105]],
    ['AC mode dorer : poulet + oignon + épices (ras el hanout, curcuma, gingembre) 5 min.', 'Ajouter carottes, courgettes, citron confit, olives et 100 ml d\'eau par portion.', '12 min sous pression, dépressurisation naturelle.', 'Semoule à part : même volume d\'eau bouillante, couvrir 5 min.'],
    'Se bonifie au frigo. Semoule à part dans la boîte.', ['marocain', 'autocuiseur', 'batch'], { pairs: ['SA07', 'SA06'] }),
  R('W08', 'Tinga de poulet, riz et haricots rouges', 'dinner', '🌮', 10, 12,
    [['poulet', 170], ['tomates_conc', 150], ['oignon', 50], ['ail', 1], ['epices', 3], ['haricots_rouges', 80], ['mais', 50], ['riz', 90], ['yaourt_grec', 60], ['avocat', 50], ['citron_vert', 10], ['herbes', 3]],
    ['AC : poulet entier + tomates + oignon + chipotle + ail, 10 min sous pression.', 'Effilocher le poulet à la fourchette directement dans la sauce, réduire 3 min en mode dorer.', 'Bowl : riz, haricots noirs, maïs, tinga, yaourt, citron vert, coriandre.'],
    'Même base en tacos un jour, en bowl le lendemain : zéro lassitude.', ['mexicain', 'autocuiseur', 'batch'], { pairs: ['SA08'] }),

  // ════ Série 2 : gourmand ════
  R('W09', 'Döner maison, sauce blanche & crudités', 'lunch', '🥙', 15, 15,
    [['haut_cuisse', 170], ['yaourt_grec', 70], ['epices', 4], ['ail', 1], ['tortilla', 120], ['salade', 40], ['tomate', 80], ['oignon', 30], ['huile', 8]],
    ['Mariner le poulet : moitié du yaourt + paprika, cumin, origan, ail.', 'AF 200°C 15 min, puis émincer finement et repasser 2 min pour griller les bords.', 'Sauce blanche : reste du yaourt + ail + herbes.', 'Au moment de manger : galette chauffée, poulet, crudités, sauce.'],
    'Le haut de cuisse reste juteux au réchauffage, c\'est le secret du döner.', ['turc', 'air fryer', 'batch', 'gourmand', 'assemblage'], { pairs: ['SA11'] }),
  R('W10', 'Smash burger & frites de patate douce', 'dinner', '🍔', 10, 20,
    [['boeuf', 150], ['pain_burger', 70], ['cheddar', 20], ['oignon', 60], ['cornichons', 15], ['yaourt_grec', 30], ['moutarde', 5], ['salade', 20], ['tomate', 50], ['patate_douce', 200], ['huile', 5]],
    ['Frites de patate douce : bâtonnets + huile + paprika fumé, AF 200°C 18 min.', 'Oignons émincés caramélisés à la poêle 10 min (se préparent pour la semaine).', 'Steak en boule, écrasé fort dans la poêle très chaude, 2 min par face, cheddar dessus.', 'Sauce : yaourt + moutarde + cornichons hachés.'],
    'En batch : oignons, sauce et frites précuites (réchauffées 4 min à l\'AF). Le steak se cuit en 4 min au moment.', ['américain', 'air fryer', 'poêle', 'gourmand', 'assemblage'], { pairs: ['SA12'] }),
  R('W11', 'Poulet croustillant à la coréenne', 'dinner', '🍗', 15, 16,
    [['haut_cuisse', 180], ['fecule', 12], ['miel', 12], ['soja', 15], ['ketchup', 15], ['epices', 1], ['ail', 1], ['riz', 90], ['concombre', 120], ['vinaigre_cidre', 5], ['sesame', 4]],
    ['Poulet en morceaux enrobé de fécule.', 'AF 200°C 16 min, secouer 2 fois : ça croustille sans friture.', 'Sauce : gochujang + miel + soja + ail, 1 min à la poêle, enrober le poulet.', 'Riz + concombre smashé (vinaigre de riz, huile de sésame, sésame).'],
    'Réchauffe le poulet à l\'AF (4 min) plutôt qu\'au micro-ondes pour retrouver le croustillant.', ['coréen', 'air fryer', 'gourmand', 'batch'], { pairs: ['SA12'] }),
  R('W12', 'Katsu curry japonais', 'dinner', '🍛', 15, 15,
    [['poulet', 160], ['chapelure', 25], ['oeuf', 1], ['riz', 65], ['carotte', 80], ['oignon', 60], ['pdt', 50], ['epices', 6], ['fecule', 8], ['miel', 5], ['soja', 5], ['huile', 8]],
    ['Sauce à l\'AC : oignon, carotte, pomme de terre, curry en poudre, miel, soja + 200 ml d\'eau, 5 min sous pression.', 'Mixer ou écraser la sauce, épaissir avec la fécule délayée.', 'Poulet aplati, œuf battu puis panko, AF 200°C 12-14 min.', 'Trancher le katsu, servir sur le riz nappé de sauce.'],
    'Les légumes mixés font une sauce onctueuse sans roux au beurre.', ['japonais', 'air fryer', 'autocuiseur', 'gourmand', 'batch'], { pairs: ['SA04'] }),
  R('W13', 'Bánh mì au poulet', 'lunch', '🥖', 15, 14,
    [['poulet', 170], ['ail', 1], ['citron_vert', 10], ['soja', 10], ['miel', 6], ['carotte', 60], ['vinaigre_cidre', 20], ['concombre', 60], ['yaourt_grec', 40], ['epices', 1], ['baguette', 125], ['herbes', 3]],
    ['Pickles express : carotte en julienne + vinaigre de riz + 1 pincée de sucre, 30 min (se gardent 1 semaine).', 'Poulet mariné citronnelle-nuoc mam-miel, AF 200°C 12-14 min, émincé.', 'Mayo légère : yaourt + sriracha.', 'Au moment : baguette passée 2 min à l\'AF, garnir.'],
    'Les pickles maison font tout le goût, pour presque zéro calorie.', ['vietnamien', 'air fryer', 'gourmand', 'assemblage']),
  R('W14', 'Butter chicken & riz complet', 'dinner', '🧈', 10, 12,
    [['poulet', 170], ['yaourt_grec', 50], ['tomates_conc', 150], ['concentre', 15], ['creme', 30], ['oignon', 50], ['gingembre', 5], ['ail', 1], ['epices', 6], ['riz', 75]],
    ['Mariner le poulet dans yaourt + garam masala (10 min ou la veille).', 'AC dorer : oignon, ail, gingembre, épices 3 min.', 'Ajouter tomates, concentré, poulet, 6 min sous pression.', 'Hors du feu, ajouter la crème. Riz basmati à part.'],
    '30 ml de crème légère suffisent : le yaourt fait le crémeux.', ['indien', 'autocuiseur', 'gourmand', 'batch'], { pairs: ['SA06'] }),
  R('W15', 'Pollo a la brasa, frites & salsa verde', 'dinner', '🍗', 10, 38,
    [['haut_cuisse', 200], ['epices', 5], ['soja', 5], ['citron_vert', 20], ['ail', 1], ['pdt', 250], ['huile', 6], ['salade', 60], ['tomate', 80], ['herbes', 15], ['yaourt_grec', 30]],
    ['Mariner le poulet : cumin, paprika, origan, soja, citron vert, ail.', 'Frites : AF 200°C 12 min, puis ajouter le poulet et cuire encore 10-12 min ensemble.', 'Salsa verde : coriandre ou persil mixés + yaourt + citron vert + piment.', 'Salade tomate à côté.'],
    'Tout cuit en même temps dans l\'air fryer.', ['péruvien', 'air fryer', 'gourmand', 'batch'], { pairs: ['SA05'] }),
  R('W16', 'Lahmacun express sur tortilla', 'lunch', '🫓', 10, 8,
    [['boeuf', 140], ['tortilla', 120], ['tomate', 100], ['poivron', 60], ['oignon', 40], ['concentre', 15], ['epices', 4], ['herbes', 15], ['citron', 15], ['salade', 50], ['huile', 6]],
    ['Garniture : bœuf cru + tomate, poivron, oignon mixés finement + concentré + paprika, cumin, piment.', 'Étaler finement sur les tortillas.', 'AF 200°C 6-7 min, jusqu\'à ce que les bords croustillent.', 'Persil, oignon, citron, rouler et manger.'],
    'La garniture se prépare pour 4 jours. Cuisson minute de 6 minutes.', ['turc', 'air fryer', 'gourmand', 'assemblage'], { pairs: ['SA03'] }),
  R('W17', 'Quesadillas poulet, haricots rouges et maïs', 'lunch', '🧀', 10, 10,
    [['poulet', 140], ['tortilla', 120], ['haricots_rouges', 80], ['mais', 50], ['emmental', 30], ['poivron', 60], ['oignon', 30], ['epices', 3], ['tomate', 80], ['citron_vert', 10], ['yaourt_grec', 40]],
    ['Poulet en dés + poivron + oignon + épices tex-mex, poêle 7 min (garniture batch).', 'Écraser grossièrement les haricots noirs.', 'Tortilla : haricots, garniture, maïs, fromage, refermer.', 'AF 190°C 5 min. Salsa tomate-citron vert et crème au yaourt.'],
    'La garniture se garde 4 jours ; l\'assemblage prend 2 min.', ['mexicain', 'air fryer', 'gourmand', 'assemblage'], { pairs: ['SA08'] }),
  R('W18', 'Nouilles sautées aux crevettes, façon pad thaï', 'dinner', '🍤', 15, 10,
    [['crevettes', 160], ['nouilles_oeufs', 90], ['oeuf', 1], ['carotte', 60], ['poivron', 80], ['soja', 15], ['miel', 10], ['citron_vert', 15], ['cacahuetes', 15], ['huile', 5]],
    ['Nouilles trempées dans l\'eau chaude 8 min.', 'Sauce : nuoc mam + miel + citron vert + soja.', 'Poêle très chaude : crevettes 2 min, œuf brouillé, carotte.', 'Nouilles + sauce 2 min, pousses de soja et cacahuètes à la fin.'],
    'Version allégée : plus de légumes, moins de nouilles. Marche aussi avec du poulet.', ['thaï', 'poêle', 'gourmand', 'batch']),

  // ════ Série 3 : rééquilibrage des protéines ════
  R('W19', 'Larb de poulet, citron vert & herbes', 'dinner', '🌿', 10, 8,
    [['poulet_hache', 170], ['riz', 90], ['citron_vert', 20], ['soja', 15], ['oignon', 40], ['epices', 1], ['cacahuetes', 15], ['concombre', 100], ['salade', 30], ['herbes', 5]],
    ['Poêle sans matière grasse : poulet haché 6-7 min en émiettant.', 'Hors du feu : nuoc mam, citron vert, échalote, piment, menthe et coriandre.', 'Servir avec riz, concombre et feuilles de salade.'],
    'Ultra frais, ultra rapide, et léger en gras.', ['thaï', 'poêle', 'batch', 'rapide']),
  R('W20', 'Bibimbap au bœuf', 'dinner', '🥗', 15, 12,
    [['boeuf_emince', 160], ['soja', 20], ['carotte', 60], ['courgette', 80], ['epinards', 60], ['huile', 5], ['oeuf', 1], ['riz', 90], ['miel', 8], ['ketchup', 10], ['epices', 1], ['sesame', 3]],
    ['Mariner le bœuf : soja, ail, huile de sésame.', 'Poêle : chaque légume 2-3 min séparément, puis le bœuf 3 min.', 'Œuf au plat ou mollet au moment.', 'Bol : riz, légumes en secteurs, bœuf, œuf, gochujang.'],
    'Légumes rangés en compartiments dans la boîte : c\'est aussi beau à J+3.', ['coréen', 'poêle', 'batch']),
  R('W21', 'Mapo tofu au bœuf', 'dinner', '🌶️', 10, 12,
    [['tofu', 120], ['boeuf', 100], ['ail', 1], ['gingembre', 5], ['huile', 5], ['soja', 15], ['ketchup', 10], ['miel', 6], ['epices', 1], ['fecule', 6], ['brocoli', 150], ['riz', 90]],
    ['Poêle : bœuf émietté 4 min avec ail et gingembre.', 'Ajouter gochujang, soja et 150 ml d\'eau.', 'Tofu en cubes, mijoter 5 min doucement, lier avec la fécule.', 'Brocoli à l\'AF ou vapeur, riz à part.'],
    'Peu de viande, beaucoup de protéines grâce au tofu : économique et réconfortant.', ['chinois', 'poêle', 'batch']),
  R('W22', 'Saumon laqué miel-soja', 'dinner', '🐟', 5, 10,
    [['saumon', 150], ['soja', 15], ['miel', 10], ['ail', 1], ['gingembre', 3], ['fecule', 3], ['brocoli', 150], ['riz', 90], ['sesame', 3]],
    ['Laque : miso + miel + 1 c.à.c d\'eau.', 'Badigeonner le saumon, AF 200°C 8-10 min avec le brocoli.', 'Concombre mariné au vinaigre de riz et sésame.', 'Servir sur le riz.'],
    'Poisson : à manger dans les 2 jours, placé en début de semaine.', ['japonais', 'air fryer', 'poisson', 'batch']),
  R('W23', 'Youvetsi : bœuf & orzo à la grecque', 'dinner', '🍝', 10, 45,
    [['boeuf_emince', 160], ['orzo', 80], ['tomates_conc', 150], ['oignon', 50], ['epices', 3], ['huile', 5], ['parmesan', 10], ['courgette', 100]],
    ['AC dorer : bœuf en cubes + oignon 5 min.', 'Tomates, cannelle, laurier + 200 ml d\'eau : 15 min sous pression.', 'Ajouter l\'orzo, la courgette et 150 ml d\'eau, 4 min sous pression.', 'Parmesan râpé au service.'],
    'Un seul récipient pour tout. La cannelle fait toute la différence.', ['grec', 'autocuiseur', 'batch']),
  R('W24', 'Gigantes : haricots blancs, tomate & feta', 'dinner', '🫘', 10, 10,
    [['haricots_blancs', 200], ['tomates_conc', 150], ['oignon', 50], ['carotte', 60], ['herbes', 8], ['huile', 8], ['feta', 30], ['pain', 80], ['epinards', 80]],
    ['AC dorer : oignon et carotte 4 min.', 'Haricots égouttés, tomates, aneth, épinards + 80 ml d\'eau : 5 min sous pression.', 'Feta émiettée au service, pain pour saucer.'],
    'Végé gourmand, économique, encore meilleur froid comme en Grèce.', ['grec', 'végé', 'autocuiseur', 'batch', 'économique']),
  R('W25', 'Tajine de kefta aux œufs', 'dinner', '🍳', 10, 20,
    [['boeuf', 150], ['oeuf', 2], ['tomates_conc', 200], ['oignon', 50], ['herbes', 10], ['epices', 4], ['pain', 80], ['huile', 8]],
    ['Petites boulettes : bœuf, persil, cumin, paprika.', 'Poêle : oignon + tomates + épices 8 min, ajouter les boulettes, 8 min.', 'En batch, garder la sauce et les boulettes ; casser les œufs dedans au réchauffage (5 min, couvert).', 'Pain pour saucer.'],
    'Les œufs se cuisent au dernier moment : tu gardes le jaune coulant.', ['marocain', 'poêle', 'batch']),
  R('W26', 'Chana masala & riz basmati', 'dinner', '🍛', 10, 10,
    [['pois_chiches', 200], ['tomates_conc', 150], ['oignon', 60], ['gingembre', 5], ['ail', 1], ['epices', 6], ['epinards', 80], ['yaourt_grec', 50], ['riz', 60], ['huile', 8]],
    ['AC dorer : oignon, ail, gingembre, garam masala, cumin 3 min.', 'Pois chiches, tomates, épinards + 100 ml d\'eau : 6 min sous pression.', 'Écraser une partie des pois chiches pour épaissir.', 'Yaourt au service, riz à part.'],
    'Tout en placard et congélateur : la recette de secours en fin de semaine.', ['indien', 'végé', 'autocuiseur', 'batch', 'économique'], { pairs: ['SA06'] }),
  R('W27', 'Lomo saltado', 'dinner', '🥩', 15, 12,
    [['boeuf_emince', 160], ['oignon', 80], ['tomate', 100], ['soja', 15], ['vinaigre_cidre', 10], ['huile', 5], ['riz', 90], ['herbes', 3]],
    ['Frites : AF 200°C 18 min.', 'Wok très chaud : bœuf en lanières 2 min, réserver.', 'Oignon rouge et tomate en quartiers 2 min, soja + vinaigre, remettre le bœuf.', 'Mélanger avec les frites juste avant de manger, riz à côté.'],
    'Garde les frites à part dans la boîte et réchauffe-les à l\'AF.', ['péruvien', 'poêle', 'air fryer', 'gourmand', 'batch']),
  R('W28', 'Moqueca de colin au lait de coco', 'dinner', '🥥', 10, 15,
    [['poisson_blanc', 200], ['citron_vert', 15], ['oignon', 50], ['poivron', 100], ['tomate', 80], ['epices', 2], ['lait_coco', 80], ['riz', 90], ['herbes', 3]],
    ['Mariner le poisson dans le citron vert 10 min.', 'Poêle : oignon, poivrons, tomates 6 min, paprika.', 'Lait de coco, poser le poisson, couvrir 8 min.', 'Coriandre, riz à part.'],
    'Colin surgelé = poisson abordable. À manger dans les 2 jours.', ['brésilien', 'poêle', 'poisson', 'batch']),
  R('W29', 'Misir wot : lentilles corail épicées et œufs', 'dinner', '🥚', 10, 10,
    [['lentilles_corail', 90], ['tomates_conc', 150], ['oignon', 50], ['ail', 1], ['gingembre', 5], ['epices', 3], ['epinards', 60], ['huile', 5], ['oeuf', 2], ['riz', 70]],
    ['AC dorer : beaucoup d\'oignon 5 min, ail, gingembre, berbéré (ou paprika + piment + cannelle).', 'Lentilles, tomates, épinards + 3 volumes d\'eau : 6 min sous pression.', 'Œufs durs (10 min) écalés, posés dessus.'],
    'Les lentilles corail fondent en purée épicée : très rassasiant pour ~1,30 €.', ['éthiopien', 'végé', 'autocuiseur', 'batch', 'économique']),
  R('W30', 'Crevettes piri-piri & riz à la tomate', 'dinner', '🦐', 10, 12,
    [['crevettes', 170], ['epices', 3], ['citron', 15], ['ail', 2], ['huile', 8], ['riz', 75], ['tomates_conc', 100], ['oignon', 40], ['poivron', 100]],
    ['Mariner les crevettes : piment, paprika, ail, citron, huile.', 'AC : riz + tomates + oignon + poivron + 1,2 volume d\'eau, 4 min sous pression.', 'Crevettes AF 200°C 6 min.', 'Servir les crevettes sur le riz.'],
    'Crevettes cuites : 2 jours au frigo maximum.', ['mozambicain', 'air fryer', 'autocuiseur', 'batch']),
];

const DEFAULT_PAIRS = { W02: ['SA03'], W13: ['SA12'], W18: ['SA12'], W19: ['SA12'], W20: ['SA12'], W21: ['SA05'], W22: ['SA04'],
  W23: ['SA05'], W24: ['SA03'], W25: ['SA02'], W27: ['SA05'], W28: ['SA01'], W29: ['SA06'], W30: ['SA08'] };
exports.mains.forEach(m => { if (!m.pairs) m.pairs = DEFAULT_PAIRS[m.id] || ['SA05']; });
const FRIES = { W04: 'SA11', W05: 'SA11', W11: 'SA01', W16: 'SA11', W17: 'SA01', W25: 'SA11' };
exports.mains.forEach(m => { if (FRIES[m.id] && !m.pairs.includes(FRIES[m.id])) m.pairs.push(FRIES[m.id]); });

exports.sides = [
  R('SA01', 'Frites de patate douce au paprika fumé', 'side', '🍠', 5, 18, [['patate_douce', 200], ['huile', 5], ['epices', 2]],
    ['Bâtonnets, huile, paprika fumé.', 'AF 200°C 16-18 min en secouant.'], 'Les sécher avec un torchon avant : plus croustillant.', ['air fryer', 'accompagnement']),
  R('SA02', 'Patatas bravas au yaourt-paprika', 'side', '🥔', 5, 18, [['pdt', 200], ['huile', 5], ['yaourt_grec', 40], ['epices', 2], ['ail', 1]],
    ['Cubes de pomme de terre + huile, AF 200°C 18 min.', 'Sauce : yaourt, paprika fumé, ail.'], '', ['air fryer', 'accompagnement']),
  R('SA03', 'Pois chiches croustillants au za\'atar', 'side', '🫘', 2, 15, [['pois_chiches', 120], ['huile', 4], ['epices', 3]],
    ['Pois chiches bien séchés + huile + za\'atar.', 'AF 190°C 14-15 min.'], 'Se grignotent aussi en collation salée.', ['air fryer', 'accompagnement']),
  R('SA04', 'Aubergine rôtie au miso', 'side', '🍆', 5, 14, [['aubergine', 200], ['miso', 10], ['miel', 5], ['sesame', 3], ['huile', 4]],
    ['Aubergine en demi-lunes quadrillées, huile.', 'AF 190°C 10 min, laquer miso-miel, encore 4 min.'], '', ['air fryer', 'accompagnement', 'japonais']),
  R('SA05', 'Brocoli rôti parmesan-citron', 'side', '🥦', 3, 10, [['brocoli', 200], ['parmesan', 10], ['citron', 10], ['huile', 4]],
    ['Fleurettes + huile, AF 200°C 8 min.', 'Parmesan, 2 min de plus, citron au service.'], '', ['air fryer', 'accompagnement']),
  R('SA06', 'Chou-fleur rôti curcuma-cumin', 'side', '🥬', 3, 15, [['chou_fleur', 200], ['huile', 5], ['epices', 3]],
    ['Fleurettes + huile + curcuma + cumin.', 'AF 200°C 14-15 min.'], '', ['air fryer', 'accompagnement', 'indien']),
  R('SA07', 'Carottes rôties miel-cumin, yaourt menthe', 'side', '🥕', 5, 16, [['carotte', 200], ['miel', 6], ['epices', 2], ['huile', 4], ['yaourt_grec', 50], ['herbes', 3]],
    ['Carottes en bâtonnets + huile + cumin, AF 190°C 14 min.', 'Miel, 2 min. Yaourt à la menthe à côté.'], '', ['air fryer', 'accompagnement', 'marocain']),
  R('SA08', 'Elote : maïs grillé, feta & citron vert', 'side', '🌽', 3, 10, [['mais', 150], ['feta', 15], ['citron_vert', 10], ['epices', 1], ['yaourt_grec', 20]],
    ['Maïs égoutté et séché, AF 200°C 10 min.', 'Yaourt, feta, piment, citron vert.'], '', ['air fryer', 'accompagnement', 'mexicain']),
  R('SA09', 'Frites de courgette panko-parmesan', 'side', '🥒', 8, 12, [['courgette', 200], ['panko', 20], ['parmesan', 10], ['yaourt_grec', 20]],
    ['Bâtonnets enrobés de yaourt, puis panko + parmesan.', 'AF 200°C 10-12 min.'], '', ['air fryer', 'accompagnement']),
  R('SA10', 'Falafels à l\'air fryer', 'side', '🧆', 10, 14, [['pois_chiches', 150], ['oignon', 30], ['herbes', 10], ['epices', 4], ['farine', 10], ['huile', 4]],
    ['Mixer pois chiches, oignon, persil, cumin, farine.', 'Former 6 boulettes, huiler, AF 190°C 14 min.'], 'Se congèlent crus.', ['air fryer', 'accompagnement', 'végé']),
  R('SA11', 'Frites maison à l\'air fryer', 'side', '🍟', 5, 18, [['pdt', 250], ['huile', 5], ['epices', 1]],
    ['Frites rincées et bien séchées + huile.', 'AF 200°C 18 min en secouant.'], '', ['air fryer', 'accompagnement']),
  R('SA12', 'Concombre smashé à la coréenne', 'side', '🥒', 5, 0, [['concombre', 200], ['vinaigre_riz', 10], ['soja', 5], ['sesame', 3], ['huile_sesame', 3], ['ail', 1]],
    ['Écraser le concombre au plat du couteau, couper.', 'Assaisonner, 10 min au frais.'], 'Sans cuisson, se garde 2 jours.', ['accompagnement', '0-cuisson', 'coréen']),
  R('W31', 'Raviolis croustillants au poulet', 'dinner', '🥟', 25, 16,
    [['poulet_hache', 180], ['feuille_riz', 64], ['courgette', 100], ['carotte', 50], ['gingembre', 5], ['ail', 1], ['soja', 15], ['huile', 5], ['citron_vert', 10], ['riz', 90]],
    ['Voir les étapes détaillées.'],
    'Croustillants sans friture : la double feuille de riz dore à l\'air fryer.', ['asiatique', 'air fryer', 'batch']),
  R('W32', 'Bol « hot honey », bœuf épicé et patate douce', 'dinner', '🍯', 10, 20,
    [['boeuf', 150], ['patate_douce', 300], ['fromage_blanc', 100], ['miel', 10], ['epices', 3], ['citron_vert', 10], ['huile', 5], ['herbes', 3]],
    ['Voir les étapes détaillées.'],
    'Sucré, piquant et frais : le fromage blanc froid sur le bœuf chaud fait tout.', ['américain', 'air fryer', 'batch']),
  R('W33', 'Pâtes crémeuses au poulet, épinards et tomates séchées', 'dinner', '🍝', 10, 12,
    [['pates', 100], ['poulet', 150], ['fromage_blanc', 120], ['parmesan', 15], ['epinards', 80], ['tomates_sechees', 25], ['ail', 1], ['huile', 5], ['epices', 1]],
    ['Voir les étapes détaillées.'],
    'Une sauce crémeuse sans crème : le fromage blanc ne doit jamais bouillir.', ['italien', 'autocuiseur', 'batch']),
  R('W34', 'Boulettes de bœuf laquées miel-ail-soja', 'dinner', '🧆', 15, 12,
    [['boeuf', 170], ['fecule', 8], ['ail', 2], ['gingembre', 4], ['soja', 20], ['miel', 12], ['vinaigre_cidre', 5], ['sesame', 4], ['riz', 90], ['concombre', 120]],
    ['Voir les étapes détaillées.'],
    'La laque se fait en 1 minute à la poêle, juste avant d\'enrober les boulettes.', ['asiatique', 'air fryer', 'batch']),
  R('W35', 'Tasty crousty healthy', 'dinner', '🍗', 15, 14,
    [['poulet', 180], ['cornflakes', 30], ['yaourt_grec', 70], ['epices', 3], ['huile', 5], ['riz', 90], ['mayo_allegee', 15], ['soja', 3], ['sauce_chili', 12], ['sriracha', 6], ['oignons_frits', 10]],
    ['Voir les étapes détaillées.'],
    'Le croustillant vient des corn-flakes écrasés, sans friture.', ['fast-food', 'air fryer', 'batch']),
  R('W36', 'Fajitas de poulet', 'dinner', '🌯', 15, 9,
    [['poulet', 160], ['poivron', 100], ['oignon', 60], ['epices', 3], ['huile', 5], ['citron_vert', 10], ['tortilla', 120], ['yaourt_grec', 60], ['tomate', 80], ['salade', 30], ['emmental', 20]],
    ['Voir les étapes détaillées.'],
    'Les poivrons doivent rester un peu croquants.', ['mexicain', 'poêle', 'batch']),
  R('W37', 'Riz sauté au poulet et à l\'œuf', 'dinner', '🍳', 15, 12,
    [['poulet', 150], ['riz', 90], ['oeuf', 1], ['petits_pois', 60], ['carotte', 50], ['oignon', 30], ['ail', 1], ['soja', 20], ['huile', 5], ['sesame', 2]],
    ['Voir les étapes détaillées.'],
    'Le riz doit être froid et un peu sec pour sauter sans coller.', ['asiatique', 'poêle', 'batch']),
  R('W38', 'Bœuf sauté aux poivrons', 'dinner', '🫑', 15, 8,
    [['boeuf_emince', 160], ['poivron', 120], ['oignon', 60], ['ail', 1], ['gingembre', 5], ['soja', 20], ['miel', 8], ['fecule', 5], ['huile', 5], ['riz', 90]],
    ['Voir les étapes détaillées.'],
    'La fécule dans la marinade garde le bœuf tendre.', ['asiatique', 'poêle', 'batch']),
  R('W39', 'Pâtes bolognaise aux légumes', 'dinner', '🍝', 10, 20,
    [['boeuf', 150], ['pates', 100], ['carotte', 60], ['courgette', 80], ['oignon', 50], ['ail', 1], ['tomates_conc', 200], ['concentre', 15], ['epices', 2], ['huile', 5], ['parmesan', 15]],
    ['Voir les étapes détaillées.'],
    'Les légumes râpés fondent dans la sauce.', ['italien', 'autocuiseur', 'batch']),
  R('W40', 'Kefta libanaises, houmous et taboulé', 'dinner', '🥙', 20, 12,
    [['boeuf', 160], ['oignon', 30], ['herbes', 10], ['epices', 3], ['boulghour', 70], ['tomate', 80], ['concombre', 80], ['citron', 15], ['huile', 5], ['houmous', 50]],
    ['Voir les étapes détaillées.'],
    'Le taboulé se fait avec le boulgour bien refroidi.', ['libanais', 'air fryer', 'batch']),
  R('W41', 'Gnocchis poêlés au poulet, tomates cerises et épinards', 'dinner', '🥔', 10, 18,
    [['poulet', 150], ['gnocchis', 200], ['tomates_cerise', 120], ['epinards', 80], ['ail', 1], ['huile', 10], ['parmesan', 15], ['epices', 1]],
    ['Voir les étapes détaillées.'],
    'Les gnocchis dorent directement à la poêle, sans les faire bouillir.', ['italien', 'poêle', 'batch']),
  R('W42', 'Nuggets maison et potatoes, sauce barbecue', 'dinner', '🍟', 20, 34,
    [['poulet', 180], ['cornflakes', 30], ['yaourt_grec', 30], ['epices', 3], ['pdt', 250], ['huile', 8], ['ketchup', 20], ['miel', 6], ['vinaigre_cidre', 5], ['soja', 5], ['carotte', 30], ['concombre', 30]],
    ['Voir les étapes détaillées.'],
    'Nuggets et potatoes dorent l\'un après l\'autre à l\'air fryer.', ['fast-food', 'air fryer', 'batch']),
  R('W43', 'Bowl kebab', 'dinner', '🥙', 15, 22,
    [['haut_cuisse', 170], ['epices', 4], ['yaourt_grec', 90], ['huile', 5], ['riz', 90], ['ail', 1], ['herbes', 2], ['salade', 40], ['tomate', 80], ['oignon', 20], ['oignons_frits', 10]],
    ['Voir les étapes détaillées.'],
    'Émincé puis regrillé 2 minutes, le poulet a le goût de la broche.', ['turc', 'air fryer', 'batch']),
  R('W44', 'Curry de colin au lait de coco et aux épinards', 'dinner', '🐟', 10, 16,
    [['poisson_blanc', 200], ['lait_coco', 80], ['epinards', 80], ['tomates_conc', 100], ['oignon', 50], ['ail', 1], ['gingembre', 5], ['epices', 5], ['huile', 5], ['citron_vert', 10], ['riz', 90]],
    ['Voir les étapes détaillées.'],
    'Le poisson cuit posé dans la sauce, sans remuer, pour rester en beaux morceaux.', ['indien', 'poêle', 'batch']),
  R('W45', 'Pâtes au thon, tomates et olives', 'dinner', '🍝', 10, 15,
    [['thon', 140], ['pates', 100], ['tomates_conc', 200], ['olives', 20], ['oignon', 40], ['ail', 1], ['huile', 5], ['epices', 1], ['parmesan', 10]],
    ['Voir les étapes détaillées.'],
    'Le thon s\'ajoute à la fin, pour garder de beaux morceaux.', ['italien', 'poêle', 'batch']),
];
